// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: game/niuniu/niuniu.proto

package niuniu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 牌型类型
type CardType int32

const (
	CardType_BULL_NO_POINT   CardType = 0  // 无点牌
	CardType_BULL_ONE        CardType = 1  // 牛一
	CardType_BULL_TWO        CardType = 2  // 牛二
	CardType_BULL_THREE      CardType = 3  // 牛三
	CardType_BULL_FOUR       CardType = 4  // 牛四
	CardType_BULL_FIVE       CardType = 5  // 牛五
	CardType_BULL_SIX        CardType = 6  // 牛六
	CardType_BULL_SEVEN      CardType = 7  // 牛七
	CardType_BULL_EIGHT      CardType = 8  // 牛八
	CardType_BULL_NINE       CardType = 9  // 牛九
	CardType_BULL_BULL       CardType = 10 // 牛牛
	CardType_BULL_FOURBOMB   CardType = 11 // 四炸
	CardType_BULL_FIVEFLOWER CardType = 12 // 五花
	CardType_BULL_FIVESMALL  CardType = 13 // 五小
)

// Enum value maps for CardType.
var (
	CardType_name = map[int32]string{
		0:  "BULL_NO_POINT",
		1:  "BULL_ONE",
		2:  "BULL_TWO",
		3:  "BULL_THREE",
		4:  "BULL_FOUR",
		5:  "BULL_FIVE",
		6:  "BULL_SIX",
		7:  "BULL_SEVEN",
		8:  "BULL_EIGHT",
		9:  "BULL_NINE",
		10: "BULL_BULL",
		11: "BULL_FOURBOMB",
		12: "BULL_FIVEFLOWER",
		13: "BULL_FIVESMALL",
	}
	CardType_value = map[string]int32{
		"BULL_NO_POINT":   0,
		"BULL_ONE":        1,
		"BULL_TWO":        2,
		"BULL_THREE":      3,
		"BULL_FOUR":       4,
		"BULL_FIVE":       5,
		"BULL_SIX":        6,
		"BULL_SEVEN":      7,
		"BULL_EIGHT":      8,
		"BULL_NINE":       9,
		"BULL_BULL":       10,
		"BULL_FOURBOMB":   11,
		"BULL_FIVEFLOWER": 12,
		"BULL_FIVESMALL":  13,
	}
)

func (x CardType) Enum() *CardType {
	p := new(CardType)
	*p = x
	return p
}

func (x CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_niuniu_niuniu_proto_enumTypes[0].Descriptor()
}

func (CardType) Type() protoreflect.EnumType {
	return &file_game_niuniu_niuniu_proto_enumTypes[0]
}

func (x CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardType.Descriptor instead.
func (CardType) EnumDescriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{0}
}

type GameStep int32

const (
	GameStep_UNKNOW        GameStep = 0
	GameStep_IDLE          GameStep = 1  // 空闲,等待玩家准备
	GameStep_COUNTDOWN     GameStep = 2  // 开始倒计时
	GameStep_BEGIN         GameStep = 3  // 开始
	GameStep_BANKER        GameStep = 4  // 抢庄
	GameStep_BANKER_NOTIFY GameStep = 5  // 通知庄
	GameStep_BET           GameStep = 6  // 下注
	GameStep_DEAL_CARDS    GameStep = 7  // 发牌
	GameStep_SHOW_CARDS    GameStep = 8  // 亮牌
	GameStep_TALLY         GameStep = 9  // 游戏结算
	GameStep_OVER          GameStep = 10 // 游戏结束
)

// Enum value maps for GameStep.
var (
	GameStep_name = map[int32]string{
		0:  "UNKNOW",
		1:  "IDLE",
		2:  "COUNTDOWN",
		3:  "BEGIN",
		4:  "BANKER",
		5:  "BANKER_NOTIFY",
		6:  "BET",
		7:  "DEAL_CARDS",
		8:  "SHOW_CARDS",
		9:  "TALLY",
		10: "OVER",
	}
	GameStep_value = map[string]int32{
		"UNKNOW":        0,
		"IDLE":          1,
		"COUNTDOWN":     2,
		"BEGIN":         3,
		"BANKER":        4,
		"BANKER_NOTIFY": 5,
		"BET":           6,
		"DEAL_CARDS":    7,
		"SHOW_CARDS":    8,
		"TALLY":         9,
		"OVER":          10,
	}
)

func (x GameStep) Enum() *GameStep {
	p := new(GameStep)
	*p = x
	return p
}

func (x GameStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStep) Descriptor() protoreflect.EnumDescriptor {
	return file_game_niuniu_niuniu_proto_enumTypes[1].Descriptor()
}

func (GameStep) Type() protoreflect.EnumType {
	return &file_game_niuniu_niuniu_proto_enumTypes[1]
}

func (x GameStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStep.Descriptor instead.
func (GameStep) EnumDescriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{1}
}

type OutCardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  CardType `protobuf:"varint,1,opt,name=type,proto3,enum=games.niuniu.CardType" json:"type,omitempty"`
	Cards []byte   `protobuf:"bytes,2,opt,name=cards,proto3" json:"cards,omitempty"` //有牛: 前三张为组成牛牛的三张牌, 其它从大到小排序
}

func (x *OutCardInfo) Reset() {
	*x = OutCardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutCardInfo) ProtoMessage() {}

func (x *OutCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutCardInfo.ProtoReflect.Descriptor instead.
func (*OutCardInfo) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{0}
}

func (x *OutCardInfo) GetType() CardType {
	if x != nil {
		return x.Type
	}
	return CardType_BULL_NO_POINT
}

func (x *OutCardInfo) GetCards() []byte {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GamePlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId    int32        `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Status    GameStep     `protobuf:"varint,2,opt,name=status,proto3,enum=games.niuniu.GameStep" json:"status,omitempty"`
	Ready     int32        `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	BankerRob int32        `protobuf:"varint,4,opt,name=banker_rob,json=bankerRob,proto3" json:"banker_rob,omitempty"` //抢庄
	Banker    bool         `protobuf:"varint,5,opt,name=banker,proto3" json:"banker,omitempty"`
	BetRate   int32        `protobuf:"varint,6,opt,name=bet_rate,json=betRate,proto3" json:"bet_rate,omitempty"`      //下注倍率
	HandCards []byte       `protobuf:"bytes,7,opt,name=hand_cards,json=handCards,proto3" json:"hand_cards,omitempty"` //
	OutCard   *OutCardInfo `protobuf:"bytes,8,opt,name=out_card,json=outCard,proto3" json:"out_card,omitempty"`
}

func (x *GamePlayerInfo) Reset() {
	*x = GamePlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamePlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePlayerInfo) ProtoMessage() {}

func (x *GamePlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePlayerInfo.ProtoReflect.Descriptor instead.
func (*GamePlayerInfo) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{1}
}

func (x *GamePlayerInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *GamePlayerInfo) GetStatus() GameStep {
	if x != nil {
		return x.Status
	}
	return GameStep_UNKNOW
}

func (x *GamePlayerInfo) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *GamePlayerInfo) GetBankerRob() int32 {
	if x != nil {
		return x.BankerRob
	}
	return 0
}

func (x *GamePlayerInfo) GetBanker() bool {
	if x != nil {
		return x.Banker
	}
	return false
}

func (x *GamePlayerInfo) GetBetRate() int32 {
	if x != nil {
		return x.BetRate
	}
	return 0
}

func (x *GamePlayerInfo) GetHandCards() []byte {
	if x != nil {
		return x.HandCards
	}
	return nil
}

func (x *GamePlayerInfo) GetOutCard() *OutCardInfo {
	if x != nil {
		return x.OutCard
	}
	return nil
}

type GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     GameStep                  `protobuf:"varint,4,opt,name=status,proto3,enum=games.niuniu.GameStep" json:"status,omitempty"` // 游戏状态
	PlayerInfo map[int32]*GamePlayerInfo `protobuf:"bytes,5,rep,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{2}
}

func (x *GameInfo) GetStatus() GameStep {
	if x != nil {
		return x.Status
	}
	return GameStep_UNKNOW
}

func (x *GameInfo) GetPlayerInfo() map[int32]*GamePlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

//游戏全量信息
type GameDeskInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameDeskInfoRequest) Reset() {
	*x = GameDeskInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameDeskInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDeskInfoRequest) ProtoMessage() {}

func (x *GameDeskInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDeskInfoRequest.ProtoReflect.Descriptor instead.
func (*GameDeskInfoRequest) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{3}
}

type GameDeskInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info     *GameInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	GameConf string    `protobuf:"bytes,2,opt,name=game_conf,json=gameConf,proto3" json:"game_conf,omitempty"`
}

func (x *GameDeskInfoResponse) Reset() {
	*x = GameDeskInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameDeskInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameDeskInfoResponse) ProtoMessage() {}

func (x *GameDeskInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameDeskInfoResponse.ProtoReflect.Descriptor instead.
func (*GameDeskInfoResponse) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{4}
}

func (x *GameDeskInfoResponse) GetInfo() *GameInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GameDeskInfoResponse) GetGameConf() string {
	if x != nil {
		return x.GameConf
	}
	return ""
}

type GameStatusNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus GameStep `protobuf:"varint,1,opt,name=game_status,json=gameStatus,proto3,enum=games.niuniu.GameStep" json:"game_status,omitempty"` // 游戏状态
	TimeDown   int32    `protobuf:"varint,3,opt,name=time_down,json=timeDown,proto3" json:"time_down,omitempty"`                                  // 倒计时
}

func (x *GameStatusNotify) Reset() {
	*x = GameStatusNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStatusNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatusNotify) ProtoMessage() {}

func (x *GameStatusNotify) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatusNotify.ProtoReflect.Descriptor instead.
func (*GameStatusNotify) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{5}
}

func (x *GameStatusNotify) GetGameStatus() GameStep {
	if x != nil {
		return x.GameStatus
	}
	return GameStep_UNKNOW
}

func (x *GameStatusNotify) GetTimeDown() int32 {
	if x != nil {
		return x.TimeDown
	}
	return 0
}

// 用户请求抢庄
type PlayerBanker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rob int32 `protobuf:"varint,2,opt,name=rob,proto3" json:"rob,omitempty"` // 1:不抢, 2: 抢
}

func (x *PlayerBanker) Reset() {
	*x = PlayerBanker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBanker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBanker) ProtoMessage() {}

func (x *PlayerBanker) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBanker.ProtoReflect.Descriptor instead.
func (*PlayerBanker) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerBanker) GetRob() int32 {
	if x != nil {
		return x.Rob
	}
	return 0
}

// 广播抢庄用户
type PlayerBankerNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId int32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Rob    int32 `protobuf:"varint,2,opt,name=rob,proto3" json:"rob,omitempty"`
}

func (x *PlayerBankerNotify) Reset() {
	*x = PlayerBankerNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBankerNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBankerNotify) ProtoMessage() {}

func (x *PlayerBankerNotify) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBankerNotify.ProtoReflect.Descriptor instead.
func (*PlayerBankerNotify) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerBankerNotify) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerBankerNotify) GetRob() int32 {
	if x != nil {
		return x.Rob
	}
	return 0
}

// 广播庄家位置
type BankerSeatNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId int32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
}

func (x *BankerSeatNotify) Reset() {
	*x = BankerSeatNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BankerSeatNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankerSeatNotify) ProtoMessage() {}

func (x *BankerSeatNotify) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankerSeatNotify.ProtoReflect.Descriptor instead.
func (*BankerSeatNotify) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{8}
}

func (x *BankerSeatNotify) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

// 闲家下注
type PlayerBetRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate int32 `protobuf:"varint,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *PlayerBetRate) Reset() {
	*x = PlayerBetRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBetRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBetRate) ProtoMessage() {}

func (x *PlayerBetRate) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBetRate.ProtoReflect.Descriptor instead.
func (*PlayerBetRate) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerBetRate) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// 广播闲家下注倍率信息
type PlayerBetRateNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId int32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Rate   int32 `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *PlayerBetRateNotify) Reset() {
	*x = PlayerBetRateNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBetRateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBetRateNotify) ProtoMessage() {}

func (x *PlayerBetRateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBetRateNotify.ProtoReflect.Descriptor instead.
func (*PlayerBetRateNotify) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerBetRateNotify) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerBetRateNotify) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// 通知用户手牌信息
type PlayerHandCardsNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId    int32  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	HandCards []byte `protobuf:"bytes,2,opt,name=hand_cards,json=handCards,proto3" json:"hand_cards,omitempty"`
}

func (x *PlayerHandCardsNotify) Reset() {
	*x = PlayerHandCardsNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerHandCardsNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerHandCardsNotify) ProtoMessage() {}

func (x *PlayerHandCardsNotify) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerHandCardsNotify.ProtoReflect.Descriptor instead.
func (*PlayerHandCardsNotify) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerHandCardsNotify) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerHandCardsNotify) GetHandCards() []byte {
	if x != nil {
		return x.HandCards
	}
	return nil
}

// 请求上传出牌信息
type PlayerOutCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutCard *OutCardInfo `protobuf:"bytes,1,opt,name=out_card,json=outCard,proto3" json:"out_card,omitempty"`
}

func (x *PlayerOutCard) Reset() {
	*x = PlayerOutCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerOutCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOutCard) ProtoMessage() {}

func (x *PlayerOutCard) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOutCard.ProtoReflect.Descriptor instead.
func (*PlayerOutCard) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerOutCard) GetOutCard() *OutCardInfo {
	if x != nil {
		return x.OutCard
	}
	return nil
}

// 广播用户出牌结果
type PlayerOutCardNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId  int32        `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	OutCard *OutCardInfo `protobuf:"bytes,2,opt,name=out_card,json=outCard,proto3" json:"out_card,omitempty"`
}

func (x *PlayerOutCardNotify) Reset() {
	*x = PlayerOutCardNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerOutCardNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOutCardNotify) ProtoMessage() {}

func (x *PlayerOutCardNotify) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOutCardNotify.ProtoReflect.Descriptor instead.
func (*PlayerOutCardNotify) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerOutCardNotify) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerOutCardNotify) GetOutCard() *OutCardInfo {
	if x != nil {
		return x.OutCard
	}
	return nil
}

// 游戏结算
type PlayerTallyNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BankerSeatId int32                                  `protobuf:"varint,1,opt,name=banker_seat_id,json=bankerSeatId,proto3" json:"banker_seat_id,omitempty"`
	TallInfo     map[int32]*PlayerTallyNotify_TallyInfo `protobuf:"bytes,2,rep,name=tall_info,json=tallInfo,proto3" json:"tall_info,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 用户输户赢信息
}

func (x *PlayerTallyNotify) Reset() {
	*x = PlayerTallyNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerTallyNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTallyNotify) ProtoMessage() {}

func (x *PlayerTallyNotify) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTallyNotify.ProtoReflect.Descriptor instead.
func (*PlayerTallyNotify) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerTallyNotify) GetBankerSeatId() int32 {
	if x != nil {
		return x.BankerSeatId
	}
	return 0
}

func (x *PlayerTallyNotify) GetTallInfo() map[int32]*PlayerTallyNotify_TallyInfo {
	if x != nil {
		return x.TallInfo
	}
	return nil
}

type PlayerTallyNotify_TallyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId int32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Coins  int32 `protobuf:"varint,2,opt,name=coins,proto3" json:"coins,omitempty"`
}

func (x *PlayerTallyNotify_TallyInfo) Reset() {
	*x = PlayerTallyNotify_TallyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_niuniu_niuniu_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerTallyNotify_TallyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTallyNotify_TallyInfo) ProtoMessage() {}

func (x *PlayerTallyNotify_TallyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_niuniu_niuniu_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTallyNotify_TallyInfo.ProtoReflect.Descriptor instead.
func (*PlayerTallyNotify_TallyInfo) Descriptor() ([]byte, []int) {
	return file_game_niuniu_niuniu_proto_rawDescGZIP(), []int{14, 0}
}

func (x *PlayerTallyNotify_TallyInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerTallyNotify_TallyInfo) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

var File_game_niuniu_niuniu_proto protoreflect.FileDescriptor

var file_game_niuniu_niuniu_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2f, 0x6e, 0x69,
	0x75, 0x6e, 0x69, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x22, 0x4f, 0x0a, 0x0b, 0x4f, 0x75, 0x74, 0x43,
	0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69,
	0x75, 0x6e, 0x69, 0x75, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x96, 0x02, 0x0a, 0x0e, 0x47, 0x61,
	0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69,
	0x75, 0x6e, 0x69, 0x75, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x65, 0x70, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x61, 0x6e, 0x6b, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x62, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x52, 0x6f, 0x62, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61,
	0x6e, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x62, 0x61, 0x6e, 0x6b,
	0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x65, 0x74, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x34, 0x0a, 0x08,
	0x6f, 0x75, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x4f, 0x75,
	0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x22, 0xe0, 0x01, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x65, 0x70, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x47, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75,
	0x6e, 0x69, 0x75, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x5b, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x73,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5f, 0x0a, 0x14,
	0x47, 0x61, 0x6d, 0x65, 0x44, 0x65, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69,
	0x75, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x22, 0x68, 0x0a,
	0x10, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x37, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e,
	0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x65, 0x70, 0x52, 0x0a,
	0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x22, 0x20, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x62, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x62, 0x22, 0x3f, 0x0a, 0x12, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x62, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x62, 0x22, 0x2b, 0x0a, 0x10, 0x42, 0x61,
	0x6e, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x42, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x42, 0x0a, 0x13,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65,
	0x22, 0x4f, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x22, 0x45, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x34, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75,
	0x6e, 0x69, 0x75, 0x2e, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x6f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x22, 0x64, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x5f,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x22, 0xa9,
	0x02, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x62, 0x61,
	0x6e, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x4a, 0x0a, 0x09, 0x74, 0x61,
	0x6c, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x54,
	0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x74, 0x61,
	0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3a, 0x0a, 0x09, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x69,
	0x6e, 0x73, 0x1a, 0x66, 0x0a, 0x0d, 0x54, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75,
	0x6e, 0x69, 0x75, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0xef, 0x01, 0x0a, 0x08, 0x43,
	0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x55, 0x4c, 0x4c, 0x5f,
	0x4e, 0x4f, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x55,
	0x4c, 0x4c, 0x5f, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x55, 0x4c, 0x4c,
	0x5f, 0x54, 0x57, 0x4f, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x54,
	0x48, 0x52, 0x45, 0x45, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x46,
	0x4f, 0x55, 0x52, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x46, 0x49,
	0x56, 0x45, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x53, 0x49, 0x58,
	0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x53, 0x45, 0x56, 0x45, 0x4e,
	0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x45, 0x49, 0x47, 0x48, 0x54,
	0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x4e, 0x49, 0x4e, 0x45, 0x10,
	0x09, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x42, 0x55, 0x4c, 0x4c, 0x10, 0x0a,
	0x12, 0x11, 0x0a, 0x0d, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x46, 0x4f, 0x55, 0x52, 0x42, 0x4f, 0x4d,
	0x42, 0x10, 0x0b, 0x12, 0x13, 0x0a, 0x0f, 0x42, 0x55, 0x4c, 0x4c, 0x5f, 0x46, 0x49, 0x56, 0x45,
	0x46, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x10, 0x0c, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x55, 0x4c, 0x4c,
	0x5f, 0x46, 0x49, 0x56, 0x45, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x10, 0x0d, 0x2a, 0x97, 0x01, 0x0a,
	0x08, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x65, 0x70, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x41, 0x4e,
	0x4b, 0x45, 0x52, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x41, 0x4e, 0x4b, 0x45, 0x52, 0x5f,
	0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x45, 0x54, 0x10,
	0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45, 0x41, 0x4c, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x53, 0x10,
	0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x48, 0x4f, 0x57, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x53, 0x10,
	0x08, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x41, 0x4c, 0x4c, 0x59, 0x10, 0x09, 0x12, 0x08, 0x0a, 0x04,
	0x4f, 0x56, 0x45, 0x52, 0x10, 0x0a, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2f, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x3b, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_niuniu_niuniu_proto_rawDescOnce sync.Once
	file_game_niuniu_niuniu_proto_rawDescData = file_game_niuniu_niuniu_proto_rawDesc
)

func file_game_niuniu_niuniu_proto_rawDescGZIP() []byte {
	file_game_niuniu_niuniu_proto_rawDescOnce.Do(func() {
		file_game_niuniu_niuniu_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_niuniu_niuniu_proto_rawDescData)
	})
	return file_game_niuniu_niuniu_proto_rawDescData
}

var file_game_niuniu_niuniu_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_game_niuniu_niuniu_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_game_niuniu_niuniu_proto_goTypes = []interface{}{
	(CardType)(0),                       // 0: games.niuniu.CardType
	(GameStep)(0),                       // 1: games.niuniu.GameStep
	(*OutCardInfo)(nil),                 // 2: games.niuniu.OutCardInfo
	(*GamePlayerInfo)(nil),              // 3: games.niuniu.GamePlayerInfo
	(*GameInfo)(nil),                    // 4: games.niuniu.GameInfo
	(*GameDeskInfoRequest)(nil),         // 5: games.niuniu.GameDeskInfoRequest
	(*GameDeskInfoResponse)(nil),        // 6: games.niuniu.GameDeskInfoResponse
	(*GameStatusNotify)(nil),            // 7: games.niuniu.GameStatusNotify
	(*PlayerBanker)(nil),                // 8: games.niuniu.PlayerBanker
	(*PlayerBankerNotify)(nil),          // 9: games.niuniu.PlayerBankerNotify
	(*BankerSeatNotify)(nil),            // 10: games.niuniu.BankerSeatNotify
	(*PlayerBetRate)(nil),               // 11: games.niuniu.PlayerBetRate
	(*PlayerBetRateNotify)(nil),         // 12: games.niuniu.PlayerBetRateNotify
	(*PlayerHandCardsNotify)(nil),       // 13: games.niuniu.PlayerHandCardsNotify
	(*PlayerOutCard)(nil),               // 14: games.niuniu.PlayerOutCard
	(*PlayerOutCardNotify)(nil),         // 15: games.niuniu.PlayerOutCardNotify
	(*PlayerTallyNotify)(nil),           // 16: games.niuniu.PlayerTallyNotify
	nil,                                 // 17: games.niuniu.GameInfo.PlayerInfoEntry
	(*PlayerTallyNotify_TallyInfo)(nil), // 18: games.niuniu.PlayerTallyNotify.TallyInfo
	nil,                                 // 19: games.niuniu.PlayerTallyNotify.TallInfoEntry
}
var file_game_niuniu_niuniu_proto_depIdxs = []int32{
	0,  // 0: games.niuniu.OutCardInfo.type:type_name -> games.niuniu.CardType
	1,  // 1: games.niuniu.GamePlayerInfo.status:type_name -> games.niuniu.GameStep
	2,  // 2: games.niuniu.GamePlayerInfo.out_card:type_name -> games.niuniu.OutCardInfo
	1,  // 3: games.niuniu.GameInfo.status:type_name -> games.niuniu.GameStep
	17, // 4: games.niuniu.GameInfo.player_info:type_name -> games.niuniu.GameInfo.PlayerInfoEntry
	4,  // 5: games.niuniu.GameDeskInfoResponse.info:type_name -> games.niuniu.GameInfo
	1,  // 6: games.niuniu.GameStatusNotify.game_status:type_name -> games.niuniu.GameStep
	2,  // 7: games.niuniu.PlayerOutCard.out_card:type_name -> games.niuniu.OutCardInfo
	2,  // 8: games.niuniu.PlayerOutCardNotify.out_card:type_name -> games.niuniu.OutCardInfo
	19, // 9: games.niuniu.PlayerTallyNotify.tall_info:type_name -> games.niuniu.PlayerTallyNotify.TallInfoEntry
	3,  // 10: games.niuniu.GameInfo.PlayerInfoEntry.value:type_name -> games.niuniu.GamePlayerInfo
	18, // 11: games.niuniu.PlayerTallyNotify.TallInfoEntry.value:type_name -> games.niuniu.PlayerTallyNotify.TallyInfo
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_game_niuniu_niuniu_proto_init() }
func file_game_niuniu_niuniu_proto_init() {
	if File_game_niuniu_niuniu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_niuniu_niuniu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutCardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamePlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameDeskInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameDeskInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStatusNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBanker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBankerNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BankerSeatNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBetRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBetRateNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerHandCardsNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerOutCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerOutCardNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerTallyNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_niuniu_niuniu_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerTallyNotify_TallyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_niuniu_niuniu_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_niuniu_niuniu_proto_goTypes,
		DependencyIndexes: file_game_niuniu_niuniu_proto_depIdxs,
		EnumInfos:         file_game_niuniu_niuniu_proto_enumTypes,
		MessageInfos:      file_game_niuniu_niuniu_proto_msgTypes,
	}.Build()
	File_game_niuniu_niuniu_proto = out.File
	file_game_niuniu_niuniu_proto_rawDesc = nil
	file_game_niuniu_niuniu_proto_goTypes = nil
	file_game_niuniu_niuniu_proto_depIdxs = nil
}
