// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.18.1
// source: msg/surf.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_surf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_msg_surf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_msg_surf_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type AsyncMsgWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *AsyncMsgWrap) Reset() {
	*x = AsyncMsgWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_surf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncMsgWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncMsgWrap) ProtoMessage() {}

func (x *AsyncMsgWrap) ProtoReflect() protoreflect.Message {
	mi := &file_msg_surf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncMsgWrap.ProtoReflect.Descriptor instead.
func (*AsyncMsgWrap) Descriptor() ([]byte, []int) {
	return file_msg_surf_proto_rawDescGZIP(), []int{1}
}

func (x *AsyncMsgWrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AsyncMsgWrap) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type RequestMsgWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body  []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Seqid uint32 `protobuf:"varint,3,opt,name=seqid,proto3" json:"seqid,omitempty"`
}

func (x *RequestMsgWrap) Reset() {
	*x = RequestMsgWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_surf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMsgWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMsgWrap) ProtoMessage() {}

func (x *RequestMsgWrap) ProtoReflect() protoreflect.Message {
	mi := &file_msg_surf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMsgWrap.ProtoReflect.Descriptor instead.
func (*RequestMsgWrap) Descriptor() ([]byte, []int) {
	return file_msg_surf_proto_rawDescGZIP(), []int{2}
}

func (x *RequestMsgWrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestMsgWrap) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RequestMsgWrap) GetSeqid() uint32 {
	if x != nil {
		return x.Seqid
	}
	return 0
}

type ResponseMsgWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body  []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Seqid uint32 `protobuf:"varint,3,opt,name=seqid,proto3" json:"seqid,omitempty"`
	Err   *Error `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *ResponseMsgWrap) Reset() {
	*x = ResponseMsgWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_surf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMsgWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMsgWrap) ProtoMessage() {}

func (x *ResponseMsgWrap) ProtoReflect() protoreflect.Message {
	mi := &file_msg_surf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMsgWrap.ProtoReflect.Descriptor instead.
func (*ResponseMsgWrap) Descriptor() ([]byte, []int) {
	return file_msg_surf_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseMsgWrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseMsgWrap) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ResponseMsgWrap) GetSeqid() uint32 {
	if x != nil {
		return x.Seqid
	}
	return 0
}

func (x *ResponseMsgWrap) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

var File_msg_surf_proto protoreflect.FileDescriptor

var file_msg_surf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x2f, 0x73, 0x75, 0x72, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x73, 0x75, 0x72, 0x66, 0x22, 0x33, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x36, 0x0a, 0x0c, 0x41,
	0x73, 0x79, 0x6e, 0x63, 0x4d, 0x73, 0x67, 0x57, 0x72, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x22, 0x4e, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x73,
	0x67, 0x57, 0x72, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x65, 0x71, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x65,
	0x71, 0x69, 0x64, 0x22, 0x6e, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x73, 0x67, 0x57, 0x72, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x65, 0x71, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x65, 0x71, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x75, 0x72, 0x66, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03,
	0x65, 0x72, 0x72, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_msg_surf_proto_rawDescOnce sync.Once
	file_msg_surf_proto_rawDescData = file_msg_surf_proto_rawDesc
)

func file_msg_surf_proto_rawDescGZIP() []byte {
	file_msg_surf_proto_rawDescOnce.Do(func() {
		file_msg_surf_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_surf_proto_rawDescData)
	})
	return file_msg_surf_proto_rawDescData
}

var file_msg_surf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msg_surf_proto_goTypes = []interface{}{
	(*Error)(nil),           // 0: surf.Error
	(*AsyncMsgWrap)(nil),    // 1: surf.AsyncMsgWrap
	(*RequestMsgWrap)(nil),  // 2: surf.RequestMsgWrap
	(*ResponseMsgWrap)(nil), // 3: surf.ResponseMsgWrap
}
var file_msg_surf_proto_depIdxs = []int32{
	0, // 0: surf.ResponseMsgWrap.err:type_name -> surf.Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msg_surf_proto_init() }
func file_msg_surf_proto_init() {
	if File_msg_surf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_surf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_surf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncMsgWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_surf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMsgWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_surf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMsgWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_surf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_surf_proto_goTypes,
		DependencyIndexes: file_msg_surf_proto_depIdxs,
		MessageInfos:      file_msg_surf_proto_msgTypes,
	}.Build()
	File_msg_surf_proto = out.File
	file_msg_surf_proto_rawDesc = nil
	file_msg_surf_proto_goTypes = nil
	file_msg_surf_proto_depIdxs = nil
}
