// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.18.1
// source: battle.inner.proto

package battle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartBattleRequest_MSGID int32

const (
	StartBattleRequest_INVALID_MSGID StartBattleRequest_MSGID = 0
	StartBattleRequest_ID            StartBattleRequest_MSGID = 1001
)

// Enum value maps for StartBattleRequest_MSGID.
var (
	StartBattleRequest_MSGID_name = map[int32]string{
		0:    "INVALID_MSGID",
		1001: "ID",
	}
	StartBattleRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            1001,
	}
)

func (x StartBattleRequest_MSGID) Enum() *StartBattleRequest_MSGID {
	p := new(StartBattleRequest_MSGID)
	*p = x
	return p
}

func (x StartBattleRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartBattleRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_inner_proto_enumTypes[0].Descriptor()
}

func (StartBattleRequest_MSGID) Type() protoreflect.EnumType {
	return &file_battle_inner_proto_enumTypes[0]
}

func (x StartBattleRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartBattleRequest_MSGID.Descriptor instead.
func (StartBattleRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{2, 0}
}

type StartBattleResponse_MSGID int32

const (
	StartBattleResponse_INVALID_MSGID StartBattleResponse_MSGID = 0
	StartBattleResponse_ID            StartBattleResponse_MSGID = 1002
)

// Enum value maps for StartBattleResponse_MSGID.
var (
	StartBattleResponse_MSGID_name = map[int32]string{
		0:    "INVALID_MSGID",
		1002: "ID",
	}
	StartBattleResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            1002,
	}
)

func (x StartBattleResponse_MSGID) Enum() *StartBattleResponse_MSGID {
	p := new(StartBattleResponse_MSGID)
	*p = x
	return p
}

func (x StartBattleResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartBattleResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_inner_proto_enumTypes[1].Descriptor()
}

func (StartBattleResponse_MSGID) Type() protoreflect.EnumType {
	return &file_battle_inner_proto_enumTypes[1]
}

func (x StartBattleResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartBattleResponse_MSGID.Descriptor instead.
func (StartBattleResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{3, 0}
}

type BattleOverReport_MSGID int32

const (
	BattleOverReport_INVALID_MSGID BattleOverReport_MSGID = 0
	BattleOverReport_ID            BattleOverReport_MSGID = 1003
)

// Enum value maps for BattleOverReport_MSGID.
var (
	BattleOverReport_MSGID_name = map[int32]string{
		0:    "INVALID_MSGID",
		1003: "ID",
	}
	BattleOverReport_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            1003,
	}
)

func (x BattleOverReport_MSGID) Enum() *BattleOverReport_MSGID {
	p := new(BattleOverReport_MSGID)
	*p = x
	return p
}

func (x BattleOverReport_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleOverReport_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_inner_proto_enumTypes[2].Descriptor()
}

func (BattleOverReport_MSGID) Type() protoreflect.EnumType {
	return &file_battle_inner_proto_enumTypes[2]
}

func (x BattleOverReport_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleOverReport_MSGID.Descriptor instead.
func (BattleOverReport_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{4, 0}
}

type BattleOverReport_State int32

const (
	BattleOverReport_Finished  BattleOverReport_State = 0 // 完成
	BattleOverReport_Disbanded BattleOverReport_State = 1 // 解散
	BattleOverReport_Timeover  BattleOverReport_State = 2 // 超时
)

// Enum value maps for BattleOverReport_State.
var (
	BattleOverReport_State_name = map[int32]string{
		0: "Finished",
		1: "Disbanded",
		2: "Timeover",
	}
	BattleOverReport_State_value = map[string]int32{
		"Finished":  0,
		"Disbanded": 1,
		"Timeover":  2,
	}
)

func (x BattleOverReport_State) Enum() *BattleOverReport_State {
	p := new(BattleOverReport_State)
	*p = x
	return p
}

func (x BattleOverReport_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleOverReport_State) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_inner_proto_enumTypes[3].Descriptor()
}

func (BattleOverReport_State) Type() protoreflect.EnumType {
	return &file_battle_inner_proto_enumTypes[3]
}

func (x BattleOverReport_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleOverReport_State.Descriptor instead.
func (BattleOverReport_State) EnumDescriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{4, 1}
}

type BattleOverReportReceipt_MSGID int32

const (
	BattleOverReportReceipt_INVALID_MSGID BattleOverReportReceipt_MSGID = 0
	BattleOverReportReceipt_ID            BattleOverReportReceipt_MSGID = 1004
)

// Enum value maps for BattleOverReportReceipt_MSGID.
var (
	BattleOverReportReceipt_MSGID_name = map[int32]string{
		0:    "INVALID_MSGID",
		1004: "ID",
	}
	BattleOverReportReceipt_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            1004,
	}
)

func (x BattleOverReportReceipt_MSGID) Enum() *BattleOverReportReceipt_MSGID {
	p := new(BattleOverReportReceipt_MSGID)
	*p = x
	return p
}

func (x BattleOverReportReceipt_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleOverReportReceipt_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_inner_proto_enumTypes[4].Descriptor()
}

func (BattleOverReportReceipt_MSGID) Type() protoreflect.EnumType {
	return &file_battle_inner_proto_enumTypes[4]
}

func (x BattleOverReportReceipt_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleOverReportReceipt_MSGID.Descriptor instead.
func (BattleOverReportReceipt_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{5, 0}
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SeatId int32  `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Score  int64  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Role   int32  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type BattleConfigure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxGameTime int32 `protobuf:"varint,1,opt,name=max_game_time,json=maxGameTime,proto3" json:"max_game_time,omitempty"` // second
}

func (x *BattleConfigure) Reset() {
	*x = BattleConfigure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleConfigure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleConfigure) ProtoMessage() {}

func (x *BattleConfigure) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleConfigure.ProtoReflect.Descriptor instead.
func (*BattleConfigure) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{1}
}

func (x *BattleConfigure) GetMaxGameTime() int32 {
	if x != nil {
		return x.MaxGameTime
	}
	return 0
}

type StartBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameName    string           `protobuf:"bytes,1,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	GameConf    []byte           `protobuf:"bytes,2,opt,name=game_conf,json=gameConf,proto3" json:"game_conf,omitempty"`
	TableConf   *BattleConfigure `protobuf:"bytes,3,opt,name=table_conf,json=tableConf,proto3" json:"table_conf,omitempty"`
	PlayerInfos []*PlayerInfo    `protobuf:"bytes,4,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"`
}

func (x *StartBattleRequest) Reset() {
	*x = StartBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleRequest) ProtoMessage() {}

func (x *StartBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleRequest.ProtoReflect.Descriptor instead.
func (*StartBattleRequest) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{2}
}

func (x *StartBattleRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *StartBattleRequest) GetGameConf() []byte {
	if x != nil {
		return x.GameConf
	}
	return nil
}

func (x *StartBattleRequest) GetTableConf() *BattleConfigure {
	if x != nil {
		return x.TableConf
	}
	return nil
}

func (x *StartBattleRequest) GetPlayerInfos() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

type StartBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
}

func (x *StartBattleResponse) Reset() {
	*x = StartBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleResponse) ProtoMessage() {}

func (x *StartBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleResponse.ProtoReflect.Descriptor instead.
func (*StartBattleResponse) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{3}
}

func (x *StartBattleResponse) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type BattleOverReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State BattleOverReport_State                  `protobuf:"varint,1,opt,name=state,proto3,enum=innerproto.battle.BattleOverReport_State" json:"state,omitempty"`
	Tally map[int32]*BattleOverReport_BattleScore `protobuf:"bytes,2,rep,name=tally,proto3" json:"tally,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Extra []byte                                  `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (x *BattleOverReport) Reset() {
	*x = BattleOverReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleOverReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOverReport) ProtoMessage() {}

func (x *BattleOverReport) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOverReport.ProtoReflect.Descriptor instead.
func (*BattleOverReport) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{4}
}

func (x *BattleOverReport) GetState() BattleOverReport_State {
	if x != nil {
		return x.State
	}
	return BattleOverReport_Finished
}

func (x *BattleOverReport) GetTally() map[int32]*BattleOverReport_BattleScore {
	if x != nil {
		return x.Tally
	}
	return nil
}

func (x *BattleOverReport) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type BattleOverReportReceipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Errcode  int32  `protobuf:"varint,2,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg   string `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *BattleOverReportReceipt) Reset() {
	*x = BattleOverReportReceipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleOverReportReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOverReportReceipt) ProtoMessage() {}

func (x *BattleOverReportReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOverReportReceipt.ProtoReflect.Descriptor instead.
func (*BattleOverReportReceipt) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{5}
}

func (x *BattleOverReportReceipt) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleOverReportReceipt) GetErrcode() int32 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *BattleOverReportReceipt) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type BattleStatusChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId     string `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	StatusBefore int32  `protobuf:"varint,2,opt,name=status_before,json=statusBefore,proto3" json:"status_before,omitempty"`
	StatusNow    int32  `protobuf:"varint,3,opt,name=status_now,json=statusNow,proto3" json:"status_now,omitempty"`
}

func (x *BattleStatusChangeEvent) Reset() {
	*x = BattleStatusChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleStatusChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStatusChangeEvent) ProtoMessage() {}

func (x *BattleStatusChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStatusChangeEvent.ProtoReflect.Descriptor instead.
func (*BattleStatusChangeEvent) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{6}
}

func (x *BattleStatusChangeEvent) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleStatusChangeEvent) GetStatusBefore() int32 {
	if x != nil {
		return x.StatusBefore
	}
	return 0
}

func (x *BattleStatusChangeEvent) GetStatusNow() int32 {
	if x != nil {
		return x.StatusNow
	}
	return 0
}

// publish events
type BattleStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BattleStartEvent) Reset() {
	*x = BattleStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStartEvent) ProtoMessage() {}

func (x *BattleStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStartEvent.ProtoReflect.Descriptor instead.
func (*BattleStartEvent) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{7}
}

type BattleOverEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BattleOverEvent) Reset() {
	*x = BattleOverEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleOverEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOverEvent) ProtoMessage() {}

func (x *BattleOverEvent) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOverEvent.ProtoReflect.Descriptor instead.
func (*BattleOverEvent) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{8}
}

type BattleOverReport_BattleScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score int64  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Extra []byte `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (x *BattleOverReport_BattleScore) Reset() {
	*x = BattleOverReport_BattleScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battle_inner_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleOverReport_BattleScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOverReport_BattleScore) ProtoMessage() {}

func (x *BattleOverReport_BattleScore) ProtoReflect() protoreflect.Message {
	mi := &file_battle_inner_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOverReport_BattleScore.ProtoReflect.Descriptor instead.
func (*BattleOverReport_BattleScore) Descriptor() ([]byte, []int) {
	return file_battle_inner_proto_rawDescGZIP(), []int{4, 0}
}

func (x *BattleOverReport_BattleScore) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BattleOverReport_BattleScore) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_battle_inner_proto protoreflect.FileDescriptor

var file_battle_inner_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x22, 0x61, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x35, 0x0a, 0x0f, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x22, 0x0a,
	0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0xf8, 0x01, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x12, 0x41, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x40, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x23, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44,
	0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xe9, 0x07, 0x22, 0x57, 0x0a, 0x13,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64,
	0x22, 0x23, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02,
	0x49, 0x44, 0x10, 0xea, 0x07, 0x22, 0xae, 0x03, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x3f, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x05, 0x74,
	0x61, 0x6c, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x54, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x74, 0x61, 0x6c, 0x6c,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x1a, 0x39, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x1a, 0x69, 0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x45, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x23, 0x0a,
	0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x44, 0x10,
	0xeb, 0x07, 0x22, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x69, 0x73,
	0x62, 0x61, 0x6e, 0x64, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x76, 0x65, 0x72, 0x10, 0x02, 0x22, 0x8d, 0x01, 0x0a, 0x17, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73,
	0x67, 0x22, 0x23, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x02, 0x49, 0x44, 0x10, 0xec, 0x07, 0x22, 0x7a, 0x0a, 0x17, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x65, 0x66,
	0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6e, 0x6f,
	0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e,
	0x6f, 0x77, 0x22, 0x12, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x4f, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x13, 0x5a, 0x11, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_battle_inner_proto_rawDescOnce sync.Once
	file_battle_inner_proto_rawDescData = file_battle_inner_proto_rawDesc
)

func file_battle_inner_proto_rawDescGZIP() []byte {
	file_battle_inner_proto_rawDescOnce.Do(func() {
		file_battle_inner_proto_rawDescData = protoimpl.X.CompressGZIP(file_battle_inner_proto_rawDescData)
	})
	return file_battle_inner_proto_rawDescData
}

var file_battle_inner_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_battle_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_battle_inner_proto_goTypes = []any{
	(StartBattleRequest_MSGID)(0),        // 0: innerproto.battle.StartBattleRequest.MSGID
	(StartBattleResponse_MSGID)(0),       // 1: innerproto.battle.StartBattleResponse.MSGID
	(BattleOverReport_MSGID)(0),          // 2: innerproto.battle.BattleOverReport.MSGID
	(BattleOverReport_State)(0),          // 3: innerproto.battle.BattleOverReport.State
	(BattleOverReportReceipt_MSGID)(0),   // 4: innerproto.battle.BattleOverReportReceipt.MSGID
	(*PlayerInfo)(nil),                   // 5: innerproto.battle.PlayerInfo
	(*BattleConfigure)(nil),              // 6: innerproto.battle.BattleConfigure
	(*StartBattleRequest)(nil),           // 7: innerproto.battle.StartBattleRequest
	(*StartBattleResponse)(nil),          // 8: innerproto.battle.StartBattleResponse
	(*BattleOverReport)(nil),             // 9: innerproto.battle.BattleOverReport
	(*BattleOverReportReceipt)(nil),      // 10: innerproto.battle.BattleOverReportReceipt
	(*BattleStatusChangeEvent)(nil),      // 11: innerproto.battle.BattleStatusChangeEvent
	(*BattleStartEvent)(nil),             // 12: innerproto.battle.BattleStartEvent
	(*BattleOverEvent)(nil),              // 13: innerproto.battle.BattleOverEvent
	(*BattleOverReport_BattleScore)(nil), // 14: innerproto.battle.BattleOverReport.BattleScore
	nil,                                  // 15: innerproto.battle.BattleOverReport.TallyEntry
}
var file_battle_inner_proto_depIdxs = []int32{
	6,  // 0: innerproto.battle.StartBattleRequest.table_conf:type_name -> innerproto.battle.BattleConfigure
	5,  // 1: innerproto.battle.StartBattleRequest.player_infos:type_name -> innerproto.battle.PlayerInfo
	3,  // 2: innerproto.battle.BattleOverReport.state:type_name -> innerproto.battle.BattleOverReport.State
	15, // 3: innerproto.battle.BattleOverReport.tally:type_name -> innerproto.battle.BattleOverReport.TallyEntry
	14, // 4: innerproto.battle.BattleOverReport.TallyEntry.value:type_name -> innerproto.battle.BattleOverReport.BattleScore
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_battle_inner_proto_init() }
func file_battle_inner_proto_init() {
	if File_battle_inner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_battle_inner_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_inner_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BattleConfigure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_inner_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StartBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_inner_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StartBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_inner_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BattleOverReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_inner_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BattleOverReportReceipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_inner_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*BattleStatusChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_inner_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*BattleStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_inner_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*BattleOverEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battle_inner_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*BattleOverReport_BattleScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_battle_inner_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_battle_inner_proto_goTypes,
		DependencyIndexes: file_battle_inner_proto_depIdxs,
		EnumInfos:         file_battle_inner_proto_enumTypes,
		MessageInfos:      file_battle_inner_proto_msgTypes,
	}.Build()
	File_battle_inner_proto = out.File
	file_battle_inner_proto_rawDesc = nil
	file_battle_inner_proto_goTypes = nil
	file_battle_inner_proto_depIdxs = nil
}
