// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePropDetail = "prop_detail"

// PropDetail mapped from table <prop_detail>
type PropDetail struct {
	PropID    int32  `gorm:"column:prop_id;primaryKey;comment:道具" json:"prop_id"`      // 道具
	PropType  int32  `gorm:"column:prop_type;not null;comment:道具类型" json:"prop_type"`  // 道具类型
	PropGroup int32  `gorm:"column:prop_group;not null;comment:道具组" json:"prop_group"` // 道具组
	PropName  string `gorm:"column:prop_name;not null;comment:道具名称" json:"prop_name"`  // 道具名称
	PropDesc  string `gorm:"column:prop_desc;not null;comment:道具描述" json:"prop_desc"`  // 道具描述
	PropIcon  string `gorm:"column:prop_icon;not null;comment:道具图标" json:"prop_icon"`  // 道具图标
}

// TableName PropDetail's table name
func (*PropDetail) TableName() string {
	return TableNamePropDetail
}
