// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.18.1
// source: lobby.proto

package lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerStatus int32

const (
	PlayerStatus_PlayerNone         PlayerStatus = 0
	PlayerStatus_PlayerInQueue      PlayerStatus = 10
	PlayerStatus_PlayerInTable      PlayerStatus = 20
	PlayerStatus_PlayerInTableReady PlayerStatus = 21
	PlayerStatus_PlayerInGaming     PlayerStatus = 31
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0:  "PlayerNone",
		10: "PlayerInQueue",
		20: "PlayerInTable",
		21: "PlayerInTableReady",
		31: "PlayerInGaming",
	}
	PlayerStatus_value = map[string]int32{
		"PlayerNone":         0,
		"PlayerInQueue":      10,
		"PlayerInTable":      20,
		"PlayerInTableReady": 21,
		"PlayerInGaming":     31,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[0].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[0]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

type TableStatus int32

const (
	TableStatus_TableNone       TableStatus = 0
	TableStatus_TableInCreating TableStatus = 10
	TableStatus_TableInInGaming TableStatus = 31
)

// Enum value maps for TableStatus.
var (
	TableStatus_name = map[int32]string{
		0:  "TableNone",
		10: "TableInCreating",
		31: "TableInInGaming",
	}
	TableStatus_value = map[string]int32{
		"TableNone":       0,
		"TableInCreating": 10,
		"TableInInGaming": 31,
	}
)

func (x TableStatus) Enum() *TableStatus {
	p := new(TableStatus)
	*p = x
	return p
}

func (x TableStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[1].Descriptor()
}

func (TableStatus) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[1]
}

func (x TableStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableStatus.Descriptor instead.
func (TableStatus) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

type ReqLoginLobby_MSGID int32

const (
	ReqLoginLobby___inval_msgid ReqLoginLobby_MSGID = 0
	ReqLoginLobby_ID            ReqLoginLobby_MSGID = 12001
)

// Enum value maps for ReqLoginLobby_MSGID.
var (
	ReqLoginLobby_MSGID_name = map[int32]string{
		0:     "__inval_msgid",
		12001: "ID",
	}
	ReqLoginLobby_MSGID_value = map[string]int32{
		"__inval_msgid": 0,
		"ID":            12001,
	}
)

func (x ReqLoginLobby_MSGID) Enum() *ReqLoginLobby_MSGID {
	p := new(ReqLoginLobby_MSGID)
	*p = x
	return p
}

func (x ReqLoginLobby_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqLoginLobby_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[2].Descriptor()
}

func (ReqLoginLobby_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[2]
}

func (x ReqLoginLobby_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqLoginLobby_MSGID.Descriptor instead.
func (ReqLoginLobby_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{8, 0}
}

type RespLoginLobby_MSGID int32

const (
	RespLoginLobby___inval_msgid RespLoginLobby_MSGID = 0
	RespLoginLobby_ID            RespLoginLobby_MSGID = 12002
)

// Enum value maps for RespLoginLobby_MSGID.
var (
	RespLoginLobby_MSGID_name = map[int32]string{
		0:     "__inval_msgid",
		12002: "ID",
	}
	RespLoginLobby_MSGID_value = map[string]int32{
		"__inval_msgid": 0,
		"ID":            12002,
	}
)

func (x RespLoginLobby_MSGID) Enum() *RespLoginLobby_MSGID {
	p := new(RespLoginLobby_MSGID)
	*p = x
	return p
}

func (x RespLoginLobby_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespLoginLobby_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[3].Descriptor()
}

func (RespLoginLobby_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[3]
}

func (x RespLoginLobby_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespLoginLobby_MSGID.Descriptor instead.
func (RespLoginLobby_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{9, 0}
}

type ReqDispatchQue_MSGID int32

const (
	ReqDispatchQue___inval_msgid ReqDispatchQue_MSGID = 0
	ReqDispatchQue_ID            ReqDispatchQue_MSGID = 12003
)

// Enum value maps for ReqDispatchQue_MSGID.
var (
	ReqDispatchQue_MSGID_name = map[int32]string{
		0:     "__inval_msgid",
		12003: "ID",
	}
	ReqDispatchQue_MSGID_value = map[string]int32{
		"__inval_msgid": 0,
		"ID":            12003,
	}
)

func (x ReqDispatchQue_MSGID) Enum() *ReqDispatchQue_MSGID {
	p := new(ReqDispatchQue_MSGID)
	*p = x
	return p
}

func (x ReqDispatchQue_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqDispatchQue_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[4].Descriptor()
}

func (ReqDispatchQue_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[4]
}

func (x ReqDispatchQue_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqDispatchQue_MSGID.Descriptor instead.
func (ReqDispatchQue_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{10, 0}
}

type RespDispatchQue_MSGID int32

const (
	RespDispatchQue___inval_msgid RespDispatchQue_MSGID = 0
	RespDispatchQue_ID            RespDispatchQue_MSGID = 12004
)

// Enum value maps for RespDispatchQue_MSGID.
var (
	RespDispatchQue_MSGID_name = map[int32]string{
		0:     "__inval_msgid",
		12004: "ID",
	}
	RespDispatchQue_MSGID_value = map[string]int32{
		"__inval_msgid": 0,
		"ID":            12004,
	}
)

func (x RespDispatchQue_MSGID) Enum() *RespDispatchQue_MSGID {
	p := new(RespDispatchQue_MSGID)
	*p = x
	return p
}

func (x RespDispatchQue_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespDispatchQue_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[5].Descriptor()
}

func (RespDispatchQue_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[5]
}

func (x RespDispatchQue_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespDispatchQue_MSGID.Descriptor instead.
func (RespDispatchQue_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{11, 0}
}

type NotifyDispatchResult_MSGID int32

const (
	NotifyDispatchResult___inval_msgid NotifyDispatchResult_MSGID = 0
	NotifyDispatchResult_ID            NotifyDispatchResult_MSGID = 12005
)

// Enum value maps for NotifyDispatchResult_MSGID.
var (
	NotifyDispatchResult_MSGID_name = map[int32]string{
		0:     "__inval_msgid",
		12005: "ID",
	}
	NotifyDispatchResult_MSGID_value = map[string]int32{
		"__inval_msgid": 0,
		"ID":            12005,
	}
)

func (x NotifyDispatchResult_MSGID) Enum() *NotifyDispatchResult_MSGID {
	p := new(NotifyDispatchResult_MSGID)
	*p = x
	return p
}

func (x NotifyDispatchResult_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyDispatchResult_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[6].Descriptor()
}

func (NotifyDispatchResult_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[6]
}

func (x NotifyDispatchResult_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyDispatchResult_MSGID.Descriptor instead.
func (NotifyDispatchResult_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{12, 0}
}

type NotifyBattleInfo_MSGID int32

const (
	NotifyBattleInfo___invalid NotifyBattleInfo_MSGID = 0
	NotifyBattleInfo_ID        NotifyBattleInfo_MSGID = 12006
)

// Enum value maps for NotifyBattleInfo_MSGID.
var (
	NotifyBattleInfo_MSGID_name = map[int32]string{
		0:     "__invalid",
		12006: "ID",
	}
	NotifyBattleInfo_MSGID_value = map[string]int32{
		"__invalid": 0,
		"ID":        12006,
	}
)

func (x NotifyBattleInfo_MSGID) Enum() *NotifyBattleInfo_MSGID {
	p := new(NotifyBattleInfo_MSGID)
	*p = x
	return p
}

func (x NotifyBattleInfo_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyBattleInfo_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[7].Descriptor()
}

func (NotifyBattleInfo_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[7]
}

func (x NotifyBattleInfo_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyBattleInfo_MSGID.Descriptor instead.
func (NotifyBattleInfo_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{13, 0}
}

type ReqLogoutLobby_MSGID int32

const (
	ReqLogoutLobby___invalid ReqLogoutLobby_MSGID = 0
	ReqLogoutLobby_ID        ReqLogoutLobby_MSGID = 12010
)

// Enum value maps for ReqLogoutLobby_MSGID.
var (
	ReqLogoutLobby_MSGID_name = map[int32]string{
		0:     "__invalid",
		12010: "ID",
	}
	ReqLogoutLobby_MSGID_value = map[string]int32{
		"__invalid": 0,
		"ID":        12010,
	}
)

func (x ReqLogoutLobby_MSGID) Enum() *ReqLogoutLobby_MSGID {
	p := new(ReqLogoutLobby_MSGID)
	*p = x
	return p
}

func (x ReqLogoutLobby_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqLogoutLobby_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[8].Descriptor()
}

func (ReqLogoutLobby_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[8]
}

func (x ReqLogoutLobby_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqLogoutLobby_MSGID.Descriptor instead.
func (ReqLogoutLobby_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{14, 0}
}

type RespLogoutLobby_MSGID int32

const (
	RespLogoutLobby___invalid RespLogoutLobby_MSGID = 0
	RespLogoutLobby_ID        RespLogoutLobby_MSGID = 12011
)

// Enum value maps for RespLogoutLobby_MSGID.
var (
	RespLogoutLobby_MSGID_name = map[int32]string{
		0:     "__invalid",
		12011: "ID",
	}
	RespLogoutLobby_MSGID_value = map[string]int32{
		"__invalid": 0,
		"ID":        12011,
	}
)

func (x RespLogoutLobby_MSGID) Enum() *RespLogoutLobby_MSGID {
	p := new(RespLogoutLobby_MSGID)
	*p = x
	return p
}

func (x RespLogoutLobby_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespLogoutLobby_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[9].Descriptor()
}

func (RespLogoutLobby_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[9]
}

func (x RespLogoutLobby_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespLogoutLobby_MSGID.Descriptor instead.
func (RespLogoutLobby_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{15, 0}
}

type NotifyTableStatus_MSGID int32

const (
	NotifyTableStatus___invalid NotifyTableStatus_MSGID = 0
	NotifyTableStatus_ID        NotifyTableStatus_MSGID = 12020
)

// Enum value maps for NotifyTableStatus_MSGID.
var (
	NotifyTableStatus_MSGID_name = map[int32]string{
		0:     "__invalid",
		12020: "ID",
	}
	NotifyTableStatus_MSGID_value = map[string]int32{
		"__invalid": 0,
		"ID":        12020,
	}
)

func (x NotifyTableStatus_MSGID) Enum() *NotifyTableStatus_MSGID {
	p := new(NotifyTableStatus_MSGID)
	*p = x
	return p
}

func (x NotifyTableStatus_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyTableStatus_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[10].Descriptor()
}

func (NotifyTableStatus_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[10]
}

func (x NotifyTableStatus_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyTableStatus_MSGID.Descriptor instead.
func (NotifyTableStatus_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{16, 0}
}

type UserBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname     string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar       string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	RegTime      int64  `protobuf:"varint,3,opt,name=reg_time,json=regTime,proto3" json:"reg_time,omitempty"`
	RegChannelId int64  `protobuf:"varint,4,opt,name=reg_channel_id,json=regChannelId,proto3" json:"reg_channel_id,omitempty"`
}

func (x *UserBaseInfo) Reset() {
	*x = UserBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBaseInfo) ProtoMessage() {}

func (x *UserBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBaseInfo.ProtoReflect.Descriptor instead.
func (*UserBaseInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *UserBaseInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBaseInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserBaseInfo) GetRegTime() int64 {
	if x != nil {
		return x.RegTime
	}
	return 0
}

func (x *UserBaseInfo) GetRegChannelId() int64 {
	if x != nil {
		return x.RegChannelId
	}
	return 0
}

type PropItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropId    int32 `protobuf:"varint,1,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	PropGroup int32 `protobuf:"varint,2,opt,name=prop_group,json=propGroup,proto3" json:"prop_group,omitempty"`
	Count     int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *PropItem) Reset() {
	*x = PropItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropItem) ProtoMessage() {}

func (x *PropItem) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropItem.ProtoReflect.Descriptor instead.
func (*PropItem) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *PropItem) GetPropId() int32 {
	if x != nil {
		return x.PropId
	}
	return 0
}

func (x *PropItem) GetPropGroup() int32 {
	if x != nil {
		return x.PropGroup
	}
	return 0
}

func (x *PropItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type NumberMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaId    int32 `protobuf:"varint,1,opt,name=meta_id,json=metaId,proto3" json:"meta_id,omitempty"`
	MetaGroup int32 `protobuf:"varint,2,opt,name=meta_group,json=metaGroup,proto3" json:"meta_group,omitempty"`
	Value     int64 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NumberMeta) Reset() {
	*x = NumberMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberMeta) ProtoMessage() {}

func (x *NumberMeta) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberMeta.ProtoReflect.Descriptor instead.
func (*NumberMeta) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *NumberMeta) GetMetaId() int32 {
	if x != nil {
		return x.MetaId
	}
	return 0
}

func (x *NumberMeta) GetMetaGroup() int32 {
	if x != nil {
		return x.MetaGroup
	}
	return 0
}

func (x *NumberMeta) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StringMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaId    int32  `protobuf:"varint,1,opt,name=meta_id,json=metaId,proto3" json:"meta_id,omitempty"`
	MetaGroup int32  `protobuf:"varint,2,opt,name=meta_group,json=metaGroup,proto3" json:"meta_group,omitempty"`
	Value     []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringMeta) Reset() {
	*x = StringMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMeta) ProtoMessage() {}

func (x *StringMeta) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMeta.ProtoReflect.Descriptor instead.
func (*StringMeta) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *StringMeta) GetMetaId() int32 {
	if x != nil {
		return x.MetaId
	}
	return 0
}

func (x *StringMeta) GetMetaGroup() int32 {
	if x != nil {
		return x.MetaGroup
	}
	return 0
}

func (x *StringMeta) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId int32 `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{5}
}

type PlayingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerStatus PlayerStatus `protobuf:"varint,1,opt,name=player_status,json=playerStatus,proto3,enum=openproto.lobby.PlayerStatus" json:"player_status,omitempty"`
	SeatId       int32        `protobuf:"varint,4,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
}

func (x *PlayingInfo) Reset() {
	*x = PlayingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayingInfo) ProtoMessage() {}

func (x *PlayingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayingInfo.ProtoReflect.Descriptor instead.
func (*PlayingInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *PlayingInfo) GetPlayerStatus() PlayerStatus {
	if x != nil {
		return x.PlayerStatus
	}
	return PlayerStatus_PlayerNone
}

func (x *PlayingInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type TableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId     string        `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	SeatCount   int32         `protobuf:"varint,2,opt,name=seat_count,json=seatCount,proto3" json:"seat_count,omitempty"`
	TableStatus TableStatus   `protobuf:"varint,3,opt,name=table_status,json=tableStatus,proto3,enum=openproto.lobby.TableStatus" json:"table_status,omitempty"`
	Players     []*PlayerInfo `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *TableInfo) Reset() {
	*x = TableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableInfo) ProtoMessage() {}

func (x *TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableInfo.ProtoReflect.Descriptor instead.
func (*TableInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *TableInfo) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *TableInfo) GetSeatCount() int32 {
	if x != nil {
		return x.SeatCount
	}
	return 0
}

func (x *TableInfo) GetTableStatus() TableStatus {
	if x != nil {
		return x.TableStatus
	}
	return TableStatus_TableNone
}

func (x *TableInfo) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type ReqLoginLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 可空
	GameId    int32 `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameSubid int32 `protobuf:"varint,3,opt,name=game_subid,json=gameSubid,proto3" json:"game_subid,omitempty"`
}

func (x *ReqLoginLobby) Reset() {
	*x = ReqLoginLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLoginLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLoginLobby) ProtoMessage() {}

func (x *ReqLoginLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLoginLobby.ProtoReflect.Descriptor instead.
func (*ReqLoginLobby) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{8}
}

func (x *ReqLoginLobby) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqLoginLobby) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ReqLoginLobby) GetGameSubid() int32 {
	if x != nil {
		return x.GameSubid
	}
	return 0
}

type RespLoginLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag        int32         `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	BaseInfo    *UserBaseInfo `protobuf:"bytes,11,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	Props       []*PropItem   `protobuf:"bytes,12,rep,name=props,proto3" json:"props,omitempty"`
	NumMeta     []*NumberMeta `protobuf:"bytes,13,rep,name=num_meta,json=numMeta,proto3" json:"num_meta,omitempty"`
	StrMeta     []*StringMeta `protobuf:"bytes,14,rep,name=str_meta,json=strMeta,proto3" json:"str_meta,omitempty"`
	PlayingInfo *PlayingInfo  `protobuf:"bytes,15,opt,name=playing_info,json=playingInfo,proto3" json:"playing_info,omitempty"`
}

func (x *RespLoginLobby) Reset() {
	*x = RespLoginLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLoginLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLoginLobby) ProtoMessage() {}

func (x *RespLoginLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLoginLobby.ProtoReflect.Descriptor instead.
func (*RespLoginLobby) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{9}
}

func (x *RespLoginLobby) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *RespLoginLobby) GetBaseInfo() *UserBaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

func (x *RespLoginLobby) GetProps() []*PropItem {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *RespLoginLobby) GetNumMeta() []*NumberMeta {
	if x != nil {
		return x.NumMeta
	}
	return nil
}

func (x *RespLoginLobby) GetStrMeta() []*StringMeta {
	if x != nil {
		return x.StrMeta
	}
	return nil
}

func (x *RespLoginLobby) GetPlayingInfo() *PlayingInfo {
	if x != nil {
		return x.PlayingInfo
	}
	return nil
}

type ReqDispatchQue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinType int32 `protobuf:"varint,1,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`
}

func (x *ReqDispatchQue) Reset() {
	*x = ReqDispatchQue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqDispatchQue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDispatchQue) ProtoMessage() {}

func (x *ReqDispatchQue) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDispatchQue.ProtoReflect.Descriptor instead.
func (*ReqDispatchQue) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{10}
}

func (x *ReqDispatchQue) GetJoinType() int32 {
	if x != nil {
		return x.JoinType
	}
	return 0
}

type RespDispatchQue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int32 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *RespDispatchQue) Reset() {
	*x = RespDispatchQue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespDispatchQue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespDispatchQue) ProtoMessage() {}

func (x *RespDispatchQue) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespDispatchQue.ProtoReflect.Descriptor instead.
func (*RespDispatchQue) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{11}
}

func (x *RespDispatchQue) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type NotifyDispatchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyDispatchResult) Reset() {
	*x = NotifyDispatchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyDispatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDispatchResult) ProtoMessage() {}

func (x *NotifyDispatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDispatchResult.ProtoReflect.Descriptor instead.
func (*NotifyDispatchResult) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{12}
}

type NotifyBattleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyBattleInfo) Reset() {
	*x = NotifyBattleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyBattleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBattleInfo) ProtoMessage() {}

func (x *NotifyBattleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBattleInfo.ProtoReflect.Descriptor instead.
func (*NotifyBattleInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{13}
}

type ReqLogoutLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqLogoutLobby) Reset() {
	*x = ReqLogoutLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLogoutLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogoutLobby) ProtoMessage() {}

func (x *ReqLogoutLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogoutLobby.ProtoReflect.Descriptor instead.
func (*ReqLogoutLobby) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{14}
}

type RespLogoutLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int32 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *RespLogoutLobby) Reset() {
	*x = RespLogoutLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLogoutLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLogoutLobby) ProtoMessage() {}

func (x *RespLogoutLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLogoutLobby.ProtoReflect.Descriptor instead.
func (*RespLogoutLobby) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{15}
}

func (x *RespLogoutLobby) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type NotifyTableStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         TableStatus `protobuf:"varint,1,opt,name=status,proto3,enum=openproto.lobby.TableStatus" json:"status,omitempty"`
	StatusDeadline int64       `protobuf:"varint,3,opt,name=status_deadline,json=statusDeadline,proto3" json:"status_deadline,omitempty"` // 状态截至时间戳, 0表示没有
}

func (x *NotifyTableStatus) Reset() {
	*x = NotifyTableStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyTableStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTableStatus) ProtoMessage() {}

func (x *NotifyTableStatus) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTableStatus.ProtoReflect.Descriptor instead.
func (*NotifyTableStatus) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{16}
}

func (x *NotifyTableStatus) GetStatus() TableStatus {
	if x != nil {
		return x.Status
	}
	return TableStatus_TableNone
}

func (x *NotifyTableStatus) GetStatusDeadline() int64 {
	if x != nil {
		return x.StatusDeadline
	}
	return 0
}

var File_lobby_proto protoreflect.FileDescriptor

var file_lobby_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f,
	0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x22, 0x83,
	0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24,
	0x0a, 0x0e, 0x72, 0x65, 0x67, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x70, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5a,
	0x0a, 0x0a, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07,
	0x6d, 0x65, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d,
	0x65, 0x74, 0x61, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5a, 0x0a, 0x0a, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x61,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x61, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x22, 0x0a, 0x0a,
	0x08, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x6a, 0x0a, 0x0b, 0x50, 0x6c, 0x61,
	0x79, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x42, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x65, 0x61, 0x74, 0x49, 0x64, 0x22, 0xbd, 0x01, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x61, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3f, 0x0a,
	0x0c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0b, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x35,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x7e, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x75, 0x62, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x75, 0x62, 0x69, 0x64,
	0x22, 0x23, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x5f, 0x5f, 0x69,
	0x6e, 0x76, 0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02,
	0x49, 0x44, 0x10, 0xe1, 0x5d, 0x22, 0xe7, 0x02, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x3a, 0x0a, 0x09,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70,
	0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x6e, 0x75, 0x6d,
	0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x4d, 0x65, 0x74,
	0x61, 0x12, 0x36, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x0e, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x07, 0x73, 0x74, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x3f, 0x0a, 0x0c, 0x70, 0x6c, 0x61,
	0x79, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70,
	0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x23, 0x0a, 0x05, 0x4d, 0x53,
	0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x5f, 0x6d,
	0x73, 0x67, 0x69, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xe2, 0x5d, 0x22,
	0x52, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x51, 0x75,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x23,
	0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x5f, 0x5f, 0x69, 0x6e, 0x76,
	0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x44,
	0x10, 0xe3, 0x5d, 0x22, 0x4a, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x44, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x51, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x23, 0x0a, 0x05, 0x4d, 0x53,
	0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x5f, 0x6d,
	0x73, 0x67, 0x69, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xe4, 0x5d, 0x22,
	0x3b, 0x0a, 0x14, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x23, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44,
	0x12, 0x11, 0x0a, 0x0d, 0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x69,
	0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xe5, 0x5d, 0x22, 0x33, 0x0a, 0x10,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x1f, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x5f, 0x69,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xe6,
	0x5d, 0x22, 0x31, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x22, 0x1f, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09,
	0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49,
	0x44, 0x10, 0xea, 0x5d, 0x22, 0x46, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x1f, 0x0a, 0x05, 0x4d,
	0x53, 0x47, 0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xeb, 0x5d, 0x22, 0x93, 0x01, 0x0a,
	0x11, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e,
	0x65, 0x22, 0x1f, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x5f,
	0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x44, 0x10,
	0xf4, 0x5d, 0x2a, 0x70, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x10, 0x0a, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x14, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x15,
	0x12, 0x12, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x10, 0x1f, 0x2a, 0x46, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x0a, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x6e, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x10, 0x1f, 0x42, 0x1b, 0x5a, 0x09,
	0x6d, 0x73, 0x67, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0xaa, 0x02, 0x0d, 0x73, 0x72, 0x63, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lobby_proto_rawDescOnce sync.Once
	file_lobby_proto_rawDescData = file_lobby_proto_rawDesc
)

func file_lobby_proto_rawDescGZIP() []byte {
	file_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_proto_rawDescData)
	})
	return file_lobby_proto_rawDescData
}

var file_lobby_proto_enumTypes = make([]protoimpl.EnumInfo, 11)
var file_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_lobby_proto_goTypes = []any{
	(PlayerStatus)(0),               // 0: openproto.lobby.PlayerStatus
	(TableStatus)(0),                // 1: openproto.lobby.TableStatus
	(ReqLoginLobby_MSGID)(0),        // 2: openproto.lobby.ReqLoginLobby.MSGID
	(RespLoginLobby_MSGID)(0),       // 3: openproto.lobby.RespLoginLobby.MSGID
	(ReqDispatchQue_MSGID)(0),       // 4: openproto.lobby.ReqDispatchQue.MSGID
	(RespDispatchQue_MSGID)(0),      // 5: openproto.lobby.RespDispatchQue.MSGID
	(NotifyDispatchResult_MSGID)(0), // 6: openproto.lobby.NotifyDispatchResult.MSGID
	(NotifyBattleInfo_MSGID)(0),     // 7: openproto.lobby.NotifyBattleInfo.MSGID
	(ReqLogoutLobby_MSGID)(0),       // 8: openproto.lobby.ReqLogoutLobby.MSGID
	(RespLogoutLobby_MSGID)(0),      // 9: openproto.lobby.RespLogoutLobby.MSGID
	(NotifyTableStatus_MSGID)(0),    // 10: openproto.lobby.NotifyTableStatus.MSGID
	(*UserBaseInfo)(nil),            // 11: openproto.lobby.UserBaseInfo
	(*PropItem)(nil),                // 12: openproto.lobby.PropItem
	(*NumberMeta)(nil),              // 13: openproto.lobby.NumberMeta
	(*StringMeta)(nil),              // 14: openproto.lobby.StringMeta
	(*PlayerInfo)(nil),              // 15: openproto.lobby.PlayerInfo
	(*GameInfo)(nil),                // 16: openproto.lobby.GameInfo
	(*PlayingInfo)(nil),             // 17: openproto.lobby.PlayingInfo
	(*TableInfo)(nil),               // 18: openproto.lobby.TableInfo
	(*ReqLoginLobby)(nil),           // 19: openproto.lobby.ReqLoginLobby
	(*RespLoginLobby)(nil),          // 20: openproto.lobby.RespLoginLobby
	(*ReqDispatchQue)(nil),          // 21: openproto.lobby.ReqDispatchQue
	(*RespDispatchQue)(nil),         // 22: openproto.lobby.RespDispatchQue
	(*NotifyDispatchResult)(nil),    // 23: openproto.lobby.NotifyDispatchResult
	(*NotifyBattleInfo)(nil),        // 24: openproto.lobby.NotifyBattleInfo
	(*ReqLogoutLobby)(nil),          // 25: openproto.lobby.ReqLogoutLobby
	(*RespLogoutLobby)(nil),         // 26: openproto.lobby.RespLogoutLobby
	(*NotifyTableStatus)(nil),       // 27: openproto.lobby.NotifyTableStatus
}
var file_lobby_proto_depIdxs = []int32{
	0,  // 0: openproto.lobby.PlayingInfo.player_status:type_name -> openproto.lobby.PlayerStatus
	1,  // 1: openproto.lobby.TableInfo.table_status:type_name -> openproto.lobby.TableStatus
	15, // 2: openproto.lobby.TableInfo.players:type_name -> openproto.lobby.PlayerInfo
	11, // 3: openproto.lobby.RespLoginLobby.base_info:type_name -> openproto.lobby.UserBaseInfo
	12, // 4: openproto.lobby.RespLoginLobby.props:type_name -> openproto.lobby.PropItem
	13, // 5: openproto.lobby.RespLoginLobby.num_meta:type_name -> openproto.lobby.NumberMeta
	14, // 6: openproto.lobby.RespLoginLobby.str_meta:type_name -> openproto.lobby.StringMeta
	17, // 7: openproto.lobby.RespLoginLobby.playing_info:type_name -> openproto.lobby.PlayingInfo
	1,  // 8: openproto.lobby.NotifyTableStatus.status:type_name -> openproto.lobby.TableStatus
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_lobby_proto_init() }
func file_lobby_proto_init() {
	if File_lobby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lobby_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PropItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*NumberMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StringMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PlayingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ReqLoginLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RespLoginLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ReqDispatchQue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RespDispatchQue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyDispatchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyBattleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ReqLogoutLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RespLogoutLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyTableStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_proto_rawDesc,
			NumEnums:      11,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_proto_depIdxs,
		EnumInfos:         file_lobby_proto_enumTypes,
		MessageInfos:      file_lobby_proto_msgTypes,
	}.Build()
	File_lobby_proto = out.File
	file_lobby_proto_rawDesc = nil
	file_lobby_proto_goTypes = nil
	file_lobby_proto_depIdxs = nil
}
