out_dir : ./model  # 输出目录
url_tag : json # web url tag(json,db(https://github.com/google/go-querystring))
db_tag : gorm # 数据库标签(gorm,db)
simple : false # 简单输出(默认gorm标签不输出)
is_out_sql : false # 是否输出 sql 原信息
is_out_func : false # 是否输出 快捷函数
is_foreign_key : false # 是否导出外键关联
is_gui : false # 是否ui模式显示
is_table_name : true # 是否直接生成表名,列名
is_column_name: true # 是否生成列名
table_prefix: "" #表前缀
table_names: "" #指定表生成，多个表用,隔开
is_out_file_by_table_name: false # 是否根据表名生成多个model
web_tag_type: 1
is_web_tag : true # 是否打web标记(json标记前提条件)
is_web_tag_pk_hidden: false # web标记是否隐藏主键