// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.23.4
// source: lobby.proto

package lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerStatus int32

const (
	PlayerStatus_PlayerNone         PlayerStatus = 0
	PlayerStatus_PlayerInQueue      PlayerStatus = 10
	PlayerStatus_PlayerInTable      PlayerStatus = 20
	PlayerStatus_PlayerInTableReady PlayerStatus = 21
	PlayerStatus_PlayerInGaming     PlayerStatus = 31
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0:  "PlayerNone",
		10: "PlayerInQueue",
		20: "PlayerInTable",
		21: "PlayerInTableReady",
		31: "PlayerInGaming",
	}
	PlayerStatus_value = map[string]int32{
		"PlayerNone":         0,
		"PlayerInQueue":      10,
		"PlayerInTable":      20,
		"PlayerInTableReady": 21,
		"PlayerInGaming":     31,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[0].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[0]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

type TableStatus int32

const (
	TableStatus_TableNone       TableStatus = 0
	TableStatus_TableInCreating TableStatus = 10
	TableStatus_TableInInGaming TableStatus = 31
	TableStatus_TableFinished   TableStatus = 40
)

// Enum value maps for TableStatus.
var (
	TableStatus_name = map[int32]string{
		0:  "TableNone",
		10: "TableInCreating",
		31: "TableInInGaming",
		40: "TableFinished",
	}
	TableStatus_value = map[string]int32{
		"TableNone":       0,
		"TableInCreating": 10,
		"TableInInGaming": 31,
		"TableFinished":   40,
	}
)

func (x TableStatus) Enum() *TableStatus {
	p := new(TableStatus)
	*p = x
	return p
}

func (x TableStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[1].Descriptor()
}

func (TableStatus) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[1]
}

func (x TableStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableStatus.Descriptor instead.
func (TableStatus) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

type ReqLoginLobby_MSGID int32

const (
	ReqLoginLobby___INVALID__ ReqLoginLobby_MSGID = 0
	ReqLoginLobby_ID          ReqLoginLobby_MSGID = 103001
)

// Enum value maps for ReqLoginLobby_MSGID.
var (
	ReqLoginLobby_MSGID_name = map[int32]string{
		0:      "__INVALID__",
		103001: "ID",
	}
	ReqLoginLobby_MSGID_value = map[string]int32{
		"__INVALID__": 0,
		"ID":          103001,
	}
)

func (x ReqLoginLobby_MSGID) Enum() *ReqLoginLobby_MSGID {
	p := new(ReqLoginLobby_MSGID)
	*p = x
	return p
}

func (x ReqLoginLobby_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqLoginLobby_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[2].Descriptor()
}

func (ReqLoginLobby_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[2]
}

func (x ReqLoginLobby_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqLoginLobby_MSGID.Descriptor instead.
func (ReqLoginLobby_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{6, 0}
}

type RespLoginLobby_MSGID int32

const (
	RespLoginLobby___INVALID__ RespLoginLobby_MSGID = 0
	RespLoginLobby_ID          RespLoginLobby_MSGID = 103002
)

// Enum value maps for RespLoginLobby_MSGID.
var (
	RespLoginLobby_MSGID_name = map[int32]string{
		0:      "__INVALID__",
		103002: "ID",
	}
	RespLoginLobby_MSGID_value = map[string]int32{
		"__INVALID__": 0,
		"ID":          103002,
	}
)

func (x RespLoginLobby_MSGID) Enum() *RespLoginLobby_MSGID {
	p := new(RespLoginLobby_MSGID)
	*p = x
	return p
}

func (x RespLoginLobby_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespLoginLobby_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[3].Descriptor()
}

func (RespLoginLobby_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[3]
}

func (x RespLoginLobby_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespLoginLobby_MSGID.Descriptor instead.
func (RespLoginLobby_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{7, 0}
}

type RespLoginLobby_FLAG int32

const (
	// dbp returns
	RespLoginLobby_kSuccess RespLoginLobby_FLAG = 0
	// process returns
	RespLoginLobby_kOtherErr      RespLoginLobby_FLAG = 99
	RespLoginLobby_kInloining     RespLoginLobby_FLAG = 1030 // 正在登录
	RespLoginLobby_kDBPError      RespLoginLobby_FLAG = 105  // 可能是dbp超时, 或者脚本catch导致的.
	RespLoginLobby_kRoomidErr     RespLoginLobby_FLAG = 106  // 场次id 错误
	RespLoginLobby_kMinSrLimit    RespLoginLobby_FLAG = 107  // 金币低于房间限制
	RespLoginLobby_kMaxSrLimit    RespLoginLobby_FLAG = 108  // 金币超过房间限制
	RespLoginLobby_kMaxTodayWin   RespLoginLobby_FLAG = 109  // 输赢超过当日上限
	RespLoginLobby_kRoomNotFound  RespLoginLobby_FLAG = 111  // 场次没有找到
	RespLoginLobby_kNotMasterNode RespLoginLobby_FLAG = 112  // 不是主节点
	RespLoginLobby_kInOtherRoom   RespLoginLobby_FLAG = 113  // 已经在别的房间
)

// Enum value maps for RespLoginLobby_FLAG.
var (
	RespLoginLobby_FLAG_name = map[int32]string{
		0:    "kSuccess",
		99:   "kOtherErr",
		1030: "kInloining",
		105:  "kDBPError",
		106:  "kRoomidErr",
		107:  "kMinSrLimit",
		108:  "kMaxSrLimit",
		109:  "kMaxTodayWin",
		111:  "kRoomNotFound",
		112:  "kNotMasterNode",
		113:  "kInOtherRoom",
	}
	RespLoginLobby_FLAG_value = map[string]int32{
		"kSuccess":       0,
		"kOtherErr":      99,
		"kInloining":     1030,
		"kDBPError":      105,
		"kRoomidErr":     106,
		"kMinSrLimit":    107,
		"kMaxSrLimit":    108,
		"kMaxTodayWin":   109,
		"kRoomNotFound":  111,
		"kNotMasterNode": 112,
		"kInOtherRoom":   113,
	}
)

func (x RespLoginLobby_FLAG) Enum() *RespLoginLobby_FLAG {
	p := new(RespLoginLobby_FLAG)
	*p = x
	return p
}

func (x RespLoginLobby_FLAG) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespLoginLobby_FLAG) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[4].Descriptor()
}

func (RespLoginLobby_FLAG) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[4]
}

func (x RespLoginLobby_FLAG) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespLoginLobby_FLAG.Descriptor instead.
func (RespLoginLobby_FLAG) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{7, 1}
}

type ReqJoinQue_MSGID int32

const (
	ReqJoinQue___INVALID__ ReqJoinQue_MSGID = 0
	ReqJoinQue_ID          ReqJoinQue_MSGID = 103003
)

// Enum value maps for ReqJoinQue_MSGID.
var (
	ReqJoinQue_MSGID_name = map[int32]string{
		0:      "__INVALID__",
		103003: "ID",
	}
	ReqJoinQue_MSGID_value = map[string]int32{
		"__INVALID__": 0,
		"ID":          103003,
	}
)

func (x ReqJoinQue_MSGID) Enum() *ReqJoinQue_MSGID {
	p := new(ReqJoinQue_MSGID)
	*p = x
	return p
}

func (x ReqJoinQue_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqJoinQue_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[5].Descriptor()
}

func (ReqJoinQue_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[5]
}

func (x ReqJoinQue_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqJoinQue_MSGID.Descriptor instead.
func (ReqJoinQue_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{8, 0}
}

type ReqJoinQue_JoinType int32

const (
	ReqJoinQue_Noraml   ReqJoinQue_JoinType = 0 // 正常
	ReqJoinQue_NextGame ReqJoinQue_JoinType = 1 // 续桌
)

// Enum value maps for ReqJoinQue_JoinType.
var (
	ReqJoinQue_JoinType_name = map[int32]string{
		0: "Noraml",
		1: "NextGame",
	}
	ReqJoinQue_JoinType_value = map[string]int32{
		"Noraml":   0,
		"NextGame": 1,
	}
)

func (x ReqJoinQue_JoinType) Enum() *ReqJoinQue_JoinType {
	p := new(ReqJoinQue_JoinType)
	*p = x
	return p
}

func (x ReqJoinQue_JoinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqJoinQue_JoinType) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[6].Descriptor()
}

func (ReqJoinQue_JoinType) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[6]
}

func (x ReqJoinQue_JoinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqJoinQue_JoinType.Descriptor instead.
func (ReqJoinQue_JoinType) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{8, 1}
}

type RespJoinQue_MSGID int32

const (
	RespJoinQue___INVALID__ RespJoinQue_MSGID = 0
	RespJoinQue_ID          RespJoinQue_MSGID = 103004
)

// Enum value maps for RespJoinQue_MSGID.
var (
	RespJoinQue_MSGID_name = map[int32]string{
		0:      "__INVALID__",
		103004: "ID",
	}
	RespJoinQue_MSGID_value = map[string]int32{
		"__INVALID__": 0,
		"ID":          103004,
	}
)

func (x RespJoinQue_MSGID) Enum() *RespJoinQue_MSGID {
	p := new(RespJoinQue_MSGID)
	*p = x
	return p
}

func (x RespJoinQue_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespJoinQue_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[7].Descriptor()
}

func (RespJoinQue_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[7]
}

func (x RespJoinQue_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespJoinQue_MSGID.Descriptor instead.
func (RespJoinQue_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{9, 0}
}

type NotifyDispatchResult_MSGID int32

const (
	NotifyDispatchResult___INVALID__ NotifyDispatchResult_MSGID = 0
	NotifyDispatchResult_ID          NotifyDispatchResult_MSGID = 103005
)

// Enum value maps for NotifyDispatchResult_MSGID.
var (
	NotifyDispatchResult_MSGID_name = map[int32]string{
		0:      "__INVALID__",
		103005: "ID",
	}
	NotifyDispatchResult_MSGID_value = map[string]int32{
		"__INVALID__": 0,
		"ID":          103005,
	}
)

func (x NotifyDispatchResult_MSGID) Enum() *NotifyDispatchResult_MSGID {
	p := new(NotifyDispatchResult_MSGID)
	*p = x
	return p
}

func (x NotifyDispatchResult_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyDispatchResult_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[8].Descriptor()
}

func (NotifyDispatchResult_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[8]
}

func (x NotifyDispatchResult_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyDispatchResult_MSGID.Descriptor instead.
func (NotifyDispatchResult_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{10, 0}
}

type NotifyDispatchResult_FLAG int32

const (
	NotifyDispatchResult_OK                      NotifyDispatchResult_FLAG = 0
	NotifyDispatchResult_LogicNodeEmpty          NotifyDispatchResult_FLAG = 1
	NotifyDispatchResult_MaxDispatchCnt          NotifyDispatchResult_FLAG = 2 // 超过最大匹配次数
	NotifyDispatchResult_CreateRemoteTableFailed NotifyDispatchResult_FLAG = 3 // 创建桌子失败
	NotifyDispatchResult_TableFeeErr             NotifyDispatchResult_FLAG = 4 // 扣手续费失败
)

// Enum value maps for NotifyDispatchResult_FLAG.
var (
	NotifyDispatchResult_FLAG_name = map[int32]string{
		0: "OK",
		1: "LogicNodeEmpty",
		2: "MaxDispatchCnt",
		3: "CreateRemoteTableFailed",
		4: "TableFeeErr",
	}
	NotifyDispatchResult_FLAG_value = map[string]int32{
		"OK":                      0,
		"LogicNodeEmpty":          1,
		"MaxDispatchCnt":          2,
		"CreateRemoteTableFailed": 3,
		"TableFeeErr":             4,
	}
)

func (x NotifyDispatchResult_FLAG) Enum() *NotifyDispatchResult_FLAG {
	p := new(NotifyDispatchResult_FLAG)
	*p = x
	return p
}

func (x NotifyDispatchResult_FLAG) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyDispatchResult_FLAG) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[9].Descriptor()
}

func (NotifyDispatchResult_FLAG) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[9]
}

func (x NotifyDispatchResult_FLAG) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyDispatchResult_FLAG.Descriptor instead.
func (NotifyDispatchResult_FLAG) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{10, 1}
}

type ReqLogoutLobby_MSGID int32

const (
	ReqLogoutLobby___invalid ReqLogoutLobby_MSGID = 0
	ReqLogoutLobby_ID        ReqLogoutLobby_MSGID = 103006
)

// Enum value maps for ReqLogoutLobby_MSGID.
var (
	ReqLogoutLobby_MSGID_name = map[int32]string{
		0:      "__invalid",
		103006: "ID",
	}
	ReqLogoutLobby_MSGID_value = map[string]int32{
		"__invalid": 0,
		"ID":        103006,
	}
)

func (x ReqLogoutLobby_MSGID) Enum() *ReqLogoutLobby_MSGID {
	p := new(ReqLogoutLobby_MSGID)
	*p = x
	return p
}

func (x ReqLogoutLobby_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqLogoutLobby_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[10].Descriptor()
}

func (ReqLogoutLobby_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[10]
}

func (x ReqLogoutLobby_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqLogoutLobby_MSGID.Descriptor instead.
func (ReqLogoutLobby_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{11, 0}
}

type RespLogoutLobby_MSGID int32

const (
	RespLogoutLobby___invalid RespLogoutLobby_MSGID = 0
	RespLogoutLobby_ID        RespLogoutLobby_MSGID = 103007
)

// Enum value maps for RespLogoutLobby_MSGID.
var (
	RespLogoutLobby_MSGID_name = map[int32]string{
		0:      "__invalid",
		103007: "ID",
	}
	RespLogoutLobby_MSGID_value = map[string]int32{
		"__invalid": 0,
		"ID":        103007,
	}
)

func (x RespLogoutLobby_MSGID) Enum() *RespLogoutLobby_MSGID {
	p := new(RespLogoutLobby_MSGID)
	*p = x
	return p
}

func (x RespLogoutLobby_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespLogoutLobby_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[11].Descriptor()
}

func (RespLogoutLobby_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[11]
}

func (x RespLogoutLobby_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespLogoutLobby_MSGID.Descriptor instead.
func (RespLogoutLobby_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{12, 0}
}

type NotifyTableStatus_MSGID int32

const (
	NotifyTableStatus___invalid NotifyTableStatus_MSGID = 0
	NotifyTableStatus_ID        NotifyTableStatus_MSGID = 103008
)

// Enum value maps for NotifyTableStatus_MSGID.
var (
	NotifyTableStatus_MSGID_name = map[int32]string{
		0:      "__invalid",
		103008: "ID",
	}
	NotifyTableStatus_MSGID_value = map[string]int32{
		"__invalid": 0,
		"ID":        103008,
	}
)

func (x NotifyTableStatus_MSGID) Enum() *NotifyTableStatus_MSGID {
	p := new(NotifyTableStatus_MSGID)
	*p = x
	return p
}

func (x NotifyTableStatus_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyTableStatus_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[12].Descriptor()
}

func (NotifyTableStatus_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[12]
}

func (x NotifyTableStatus_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyTableStatus_MSGID.Descriptor instead.
func (NotifyTableStatus_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{13, 0}
}

type ReqUserDetailInfo_MSGID int32

const (
	ReqUserDetailInfo___invalid ReqUserDetailInfo_MSGID = 0
	ReqUserDetailInfo_ID        ReqUserDetailInfo_MSGID = 103009
)

// Enum value maps for ReqUserDetailInfo_MSGID.
var (
	ReqUserDetailInfo_MSGID_name = map[int32]string{
		0:      "__invalid",
		103009: "ID",
	}
	ReqUserDetailInfo_MSGID_value = map[string]int32{
		"__invalid": 0,
		"ID":        103009,
	}
)

func (x ReqUserDetailInfo_MSGID) Enum() *ReqUserDetailInfo_MSGID {
	p := new(ReqUserDetailInfo_MSGID)
	*p = x
	return p
}

func (x ReqUserDetailInfo_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqUserDetailInfo_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[13].Descriptor()
}

func (ReqUserDetailInfo_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[13]
}

func (x ReqUserDetailInfo_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqUserDetailInfo_MSGID.Descriptor instead.
func (ReqUserDetailInfo_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{14, 0}
}

type RespUserDetailInfo_MSGID int32

const (
	RespUserDetailInfo___invalid RespUserDetailInfo_MSGID = 0
	RespUserDetailInfo_ID        RespUserDetailInfo_MSGID = 103010
)

// Enum value maps for RespUserDetailInfo_MSGID.
var (
	RespUserDetailInfo_MSGID_name = map[int32]string{
		0:      "__invalid",
		103010: "ID",
	}
	RespUserDetailInfo_MSGID_value = map[string]int32{
		"__invalid": 0,
		"ID":        103010,
	}
)

func (x RespUserDetailInfo_MSGID) Enum() *RespUserDetailInfo_MSGID {
	p := new(RespUserDetailInfo_MSGID)
	*p = x
	return p
}

func (x RespUserDetailInfo_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespUserDetailInfo_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_lobby_proto_enumTypes[14].Descriptor()
}

func (RespUserDetailInfo_MSGID) Type() protoreflect.EnumType {
	return &file_lobby_proto_enumTypes[14]
}

func (x RespUserDetailInfo_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespUserDetailInfo_MSGID.Descriptor instead.
func (RespUserDetailInfo_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{15, 0}
}

type UserBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname     string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar       string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	RegTime      int64  `protobuf:"varint,3,opt,name=reg_time,json=regTime,proto3" json:"reg_time,omitempty"`
	RegChannelId int64  `protobuf:"varint,4,opt,name=reg_channel_id,json=regChannelId,proto3" json:"reg_channel_id,omitempty"`
}

func (x *UserBaseInfo) Reset() {
	*x = UserBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBaseInfo) ProtoMessage() {}

func (x *UserBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBaseInfo.ProtoReflect.Descriptor instead.
func (*UserBaseInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *UserBaseInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserBaseInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserBaseInfo) GetRegTime() int64 {
	if x != nil {
		return x.RegTime
	}
	return 0
}

func (x *UserBaseInfo) GetRegChannelId() int64 {
	if x != nil {
		return x.RegChannelId
	}
	return 0
}

// 用户道具数据
type UserPropInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Props map[int32]int64 `protobuf:"bytes,1,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *UserPropInfo) Reset() {
	*x = UserPropInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPropInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPropInfo) ProtoMessage() {}

func (x *UserPropInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPropInfo.ProtoReflect.Descriptor instead.
func (*UserPropInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *UserPropInfo) GetProps() map[int32]int64 {
	if x != nil {
		return x.Props
	}
	return nil
}

// 游戏数据
type UserGameBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId    int32 `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	WinCnt    int64 `protobuf:"varint,2,opt,name=win_cnt,json=winCnt,proto3" json:"win_cnt,omitempty"`
	FailCnt   int64 `protobuf:"varint,3,opt,name=fail_cnt,json=failCnt,proto3" json:"fail_cnt,omitempty"`
	DrawCnt   int64 `protobuf:"varint,4,opt,name=draw_cnt,json=drawCnt,proto3" json:"draw_cnt,omitempty"`
	Exp       int64 `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	PlayScore int64 `protobuf:"varint,6,opt,name=play_score,json=playScore,proto3" json:"play_score,omitempty"`
}

func (x *UserGameBaseInfo) Reset() {
	*x = UserGameBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGameBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGameBaseInfo) ProtoMessage() {}

func (x *UserGameBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGameBaseInfo.ProtoReflect.Descriptor instead.
func (*UserGameBaseInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *UserGameBaseInfo) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *UserGameBaseInfo) GetWinCnt() int64 {
	if x != nil {
		return x.WinCnt
	}
	return 0
}

func (x *UserGameBaseInfo) GetFailCnt() int64 {
	if x != nil {
		return x.FailCnt
	}
	return 0
}

func (x *UserGameBaseInfo) GetDrawCnt() int64 {
	if x != nil {
		return x.DrawCnt
	}
	return 0
}

func (x *UserGameBaseInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *UserGameBaseInfo) GetPlayScore() int64 {
	if x != nil {
		return x.PlayScore
	}
	return 0
}

type UserPlayingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerStatus PlayerStatus `protobuf:"varint,1,opt,name=player_status,json=playerStatus,proto3,enum=openproto.lobby.PlayerStatus" json:"player_status,omitempty"`
	BattleNodeId int32        `protobuf:"varint,5,opt,name=battle_node_id,json=battleNodeId,proto3" json:"battle_node_id,omitempty"`
	BattleId     string       `protobuf:"bytes,6,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	SeatId       int32        `protobuf:"varint,7,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
}

func (x *UserPlayingInfo) Reset() {
	*x = UserPlayingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPlayingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPlayingInfo) ProtoMessage() {}

func (x *UserPlayingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPlayingInfo.ProtoReflect.Descriptor instead.
func (*UserPlayingInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *UserPlayingInfo) GetPlayerStatus() PlayerStatus {
	if x != nil {
		return x.PlayerStatus
	}
	return PlayerStatus_PlayerNone
}

func (x *UserPlayingInfo) GetBattleNodeId() int32 {
	if x != nil {
		return x.BattleNodeId
	}
	return 0
}

func (x *UserPlayingInfo) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *UserPlayingInfo) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

type UserMetaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntMeta map[string]int64  `protobuf:"bytes,1,rep,name=int_meta,json=intMeta,proto3" json:"int_meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	StrMeta map[string]string `protobuf:"bytes,2,rep,name=str_meta,json=strMeta,proto3" json:"str_meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UserMetaInfo) Reset() {
	*x = UserMetaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMetaInfo) ProtoMessage() {}

func (x *UserMetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMetaInfo.ProtoReflect.Descriptor instead.
func (*UserMetaInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *UserMetaInfo) GetIntMeta() map[string]int64 {
	if x != nil {
		return x.IntMeta
	}
	return nil
}

func (x *UserMetaInfo) GetStrMeta() map[string]string {
	if x != nil {
		return x.StrMeta
	}
	return nil
}

type TableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId     string      `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	SeatCount   int32       `protobuf:"varint,2,opt,name=seat_count,json=seatCount,proto3" json:"seat_count,omitempty"`
	TableStatus TableStatus `protobuf:"varint,3,opt,name=table_status,json=tableStatus,proto3,enum=openproto.lobby.TableStatus" json:"table_status,omitempty"` // repeated TablePlayerInfo players = 4;
}

func (x *TableInfo) Reset() {
	*x = TableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableInfo) ProtoMessage() {}

func (x *TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableInfo.ProtoReflect.Descriptor instead.
func (*TableInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *TableInfo) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *TableInfo) GetSeatCount() int32 {
	if x != nil {
		return x.SeatCount
	}
	return 0
}

func (x *TableInfo) GetTableStatus() TableStatus {
	if x != nil {
		return x.TableStatus
	}
	return TableStatus_TableNone
}

type ReqLoginLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 可空
	GameId     int32  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameRoomId int32  `protobuf:"varint,3,opt,name=game_room_id,json=gameRoomId,proto3" json:"game_room_id,omitempty"`
}

func (x *ReqLoginLobby) Reset() {
	*x = ReqLoginLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLoginLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLoginLobby) ProtoMessage() {}

func (x *ReqLoginLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLoginLobby.ProtoReflect.Descriptor instead.
func (*ReqLoginLobby) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *ReqLoginLobby) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqLoginLobby) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ReqLoginLobby) GetGameRoomId() int32 {
	if x != nil {
		return x.GameRoomId
	}
	return 0
}

type RespLoginLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag     RespLoginLobby_FLAG `protobuf:"varint,1,opt,name=flag,proto3,enum=openproto.lobby.RespLoginLobby_FLAG" json:"flag,omitempty"`
	BaseInfo *UserBaseInfo       `protobuf:"bytes,11,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	Props    *UserPropInfo       `protobuf:"bytes,12,opt,name=props,proto3" json:"props,omitempty"`
	MetaInfo *UserMetaInfo       `protobuf:"bytes,13,opt,name=meta_info,json=metaInfo,proto3" json:"meta_info,omitempty"`
}

func (x *RespLoginLobby) Reset() {
	*x = RespLoginLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLoginLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLoginLobby) ProtoMessage() {}

func (x *RespLoginLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLoginLobby.ProtoReflect.Descriptor instead.
func (*RespLoginLobby) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *RespLoginLobby) GetFlag() RespLoginLobby_FLAG {
	if x != nil {
		return x.Flag
	}
	return RespLoginLobby_kSuccess
}

func (x *RespLoginLobby) GetBaseInfo() *UserBaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

func (x *RespLoginLobby) GetProps() *UserPropInfo {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *RespLoginLobby) GetMetaInfo() *UserMetaInfo {
	if x != nil {
		return x.MetaInfo
	}
	return nil
}

type ReqJoinQue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinType ReqJoinQue_JoinType `protobuf:"varint,1,opt,name=join_type,json=joinType,proto3,enum=openproto.lobby.ReqJoinQue_JoinType" json:"join_type,omitempty"`
}

func (x *ReqJoinQue) Reset() {
	*x = ReqJoinQue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqJoinQue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqJoinQue) ProtoMessage() {}

func (x *ReqJoinQue) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqJoinQue.ProtoReflect.Descriptor instead.
func (*ReqJoinQue) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{8}
}

func (x *ReqJoinQue) GetJoinType() ReqJoinQue_JoinType {
	if x != nil {
		return x.JoinType
	}
	return ReqJoinQue_Noraml
}

type RespJoinQue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag       int32 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	DispatchId int32 `protobuf:"varint,2,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
}

func (x *RespJoinQue) Reset() {
	*x = RespJoinQue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinQue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinQue) ProtoMessage() {}

func (x *RespJoinQue) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinQue.ProtoReflect.Descriptor instead.
func (*RespJoinQue) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{9}
}

func (x *RespJoinQue) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *RespJoinQue) GetDispatchId() int32 {
	if x != nil {
		return x.DispatchId
	}
	return 0
}

type NotifyDispatchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag         NotifyDispatchResult_FLAG           `protobuf:"varint,1,opt,name=flag,proto3,enum=openproto.lobby.NotifyDispatchResult_FLAG" json:"flag,omitempty"`
	BattleNodeId int32                               `protobuf:"varint,2,opt,name=battle_node_id,json=battleNodeId,proto3" json:"battle_node_id,omitempty"` // logic_process appid
	BattleId     string                              `protobuf:"bytes,3,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Players      []*NotifyDispatchResult_TablePlayer `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *NotifyDispatchResult) Reset() {
	*x = NotifyDispatchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyDispatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDispatchResult) ProtoMessage() {}

func (x *NotifyDispatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDispatchResult.ProtoReflect.Descriptor instead.
func (*NotifyDispatchResult) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyDispatchResult) GetFlag() NotifyDispatchResult_FLAG {
	if x != nil {
		return x.Flag
	}
	return NotifyDispatchResult_OK
}

func (x *NotifyDispatchResult) GetBattleNodeId() int32 {
	if x != nil {
		return x.BattleNodeId
	}
	return 0
}

func (x *NotifyDispatchResult) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *NotifyDispatchResult) GetPlayers() []*NotifyDispatchResult_TablePlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type ReqLogoutLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ReqLogoutLobby) Reset() {
	*x = ReqLogoutLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLogoutLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogoutLobby) ProtoMessage() {}

func (x *ReqLogoutLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogoutLobby.ProtoReflect.Descriptor instead.
func (*ReqLogoutLobby) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{11}
}

func (x *ReqLogoutLobby) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type RespLogoutLobby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int32 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *RespLogoutLobby) Reset() {
	*x = RespLogoutLobby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLogoutLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLogoutLobby) ProtoMessage() {}

func (x *RespLogoutLobby) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLogoutLobby.ProtoReflect.Descriptor instead.
func (*RespLogoutLobby) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{12}
}

func (x *RespLogoutLobby) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type NotifyTableStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         TableStatus `protobuf:"varint,1,opt,name=status,proto3,enum=openproto.lobby.TableStatus" json:"status,omitempty"`
	StatusDeadline int64       `protobuf:"varint,3,opt,name=status_deadline,json=statusDeadline,proto3" json:"status_deadline,omitempty"` // 状态截至时间戳, 0表示没有
}

func (x *NotifyTableStatus) Reset() {
	*x = NotifyTableStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyTableStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTableStatus) ProtoMessage() {}

func (x *NotifyTableStatus) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTableStatus.ProtoReflect.Descriptor instead.
func (*NotifyTableStatus) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyTableStatus) GetStatus() TableStatus {
	if x != nil {
		return x.Status
	}
	return TableStatus_TableNone
}

func (x *NotifyTableStatus) GetStatusDeadline() int64 {
	if x != nil {
		return x.StatusDeadline
	}
	return 0
}

type ReqUserDetailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid []int64 `protobuf:"varint,1,rep,packed,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ReqUserDetailInfo) Reset() {
	*x = ReqUserDetailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserDetailInfo) ProtoMessage() {}

func (x *ReqUserDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserDetailInfo.ProtoReflect.Descriptor instead.
func (*ReqUserDetailInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{14}
}

func (x *ReqUserDetailInfo) GetUid() []int64 {
	if x != nil {
		return x.Uid
	}
	return nil
}

type RespUserDetailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users map[int64]*UserBaseInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RespUserDetailInfo) Reset() {
	*x = RespUserDetailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespUserDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespUserDetailInfo) ProtoMessage() {}

func (x *RespUserDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespUserDetailInfo.ProtoReflect.Descriptor instead.
func (*RespUserDetailInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{15}
}

func (x *RespUserDetailInfo) GetUsers() map[int64]*UserBaseInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type NotifyDispatchResult_TablePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SeatId   int32  `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Score    int64  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *NotifyDispatchResult_TablePlayer) Reset() {
	*x = NotifyDispatchResult_TablePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyDispatchResult_TablePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDispatchResult_TablePlayer) ProtoMessage() {}

func (x *NotifyDispatchResult_TablePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDispatchResult_TablePlayer.ProtoReflect.Descriptor instead.
func (*NotifyDispatchResult_TablePlayer) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{10, 0}
}

func (x *NotifyDispatchResult_TablePlayer) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *NotifyDispatchResult_TablePlayer) GetSeatId() int32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *NotifyDispatchResult_TablePlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *NotifyDispatchResult_TablePlayer) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_lobby_proto protoreflect.FileDescriptor

var file_lobby_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f,
	0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x22, 0x83,
	0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24,
	0x0a, 0x0e, 0x72, 0x65, 0x67, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x49, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3e, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x70, 0x72, 0x6f, 0x70, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xab, 0x01, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x61, 0x73, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x77, 0x69, 0x6e, 0x5f, 0x63, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x77, 0x69, 0x6e, 0x43, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x63,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x43, 0x6e,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x63, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x72, 0x61, 0x77, 0x43, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0xb1, 0x01,
	0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x42, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49,
	0x64, 0x22, 0x94, 0x02, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x45, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x69, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x45, 0x0a, 0x08, 0x73, 0x74, 0x72,
	0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x4d, 0x65,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x74, 0x72, 0x4d, 0x65, 0x74, 0x61,
	0x1a, 0x3a, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3a, 0x0a, 0x0c,
	0x53, 0x74, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x86, 0x01, 0x0a, 0x09, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x61, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x3f, 0x0a, 0x0c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x80, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x5f, 0x5f, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x5f, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x02, 0x49, 0x44,
	0x10, 0xd9, 0xa4, 0x06, 0x22, 0xde, 0x03, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x38, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x46, 0x4c, 0x41, 0x47, 0x52, 0x04, 0x66, 0x6c, 0x61,
	0x67, 0x12, 0x3a, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a,
	0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x70, 0x72, 0x6f,
	0x70, 0x73, 0x12, 0x3a, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x22,
	0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x5f, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x5f, 0x5f, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xda,
	0xa4, 0x06, 0x22, 0xc0, 0x01, 0x0a, 0x04, 0x46, 0x4c, 0x41, 0x47, 0x12, 0x0c, 0x0a, 0x08, 0x6b,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x6b, 0x4f, 0x74,
	0x68, 0x65, 0x72, 0x45, 0x72, 0x72, 0x10, 0x63, 0x12, 0x0f, 0x0a, 0x0a, 0x6b, 0x49, 0x6e, 0x6c,
	0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x86, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x6b, 0x44, 0x42,
	0x50, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x69, 0x12, 0x0e, 0x0a, 0x0a, 0x6b, 0x52, 0x6f, 0x6f,
	0x6d, 0x69, 0x64, 0x45, 0x72, 0x72, 0x10, 0x6a, 0x12, 0x0f, 0x0a, 0x0b, 0x6b, 0x4d, 0x69, 0x6e,
	0x53, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x10, 0x6b, 0x12, 0x0f, 0x0a, 0x0b, 0x6b, 0x4d, 0x61,
	0x78, 0x53, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x10, 0x6c, 0x12, 0x10, 0x0a, 0x0c, 0x6b, 0x4d,
	0x61, 0x78, 0x54, 0x6f, 0x64, 0x61, 0x79, 0x57, 0x69, 0x6e, 0x10, 0x6d, 0x12, 0x11, 0x0a, 0x0d,
	0x6b, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x6f, 0x12,
	0x12, 0x0a, 0x0e, 0x6b, 0x4e, 0x6f, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64,
	0x65, 0x10, 0x70, 0x12, 0x10, 0x0a, 0x0c, 0x6b, 0x49, 0x6e, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x52,
	0x6f, 0x6f, 0x6d, 0x10, 0x71, 0x22, 0x99, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69,
	0x6e, 0x51, 0x75, 0x65, 0x12, 0x41, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69,
	0x6e, 0x51, 0x75, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6a,
	0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44,
	0x12, 0x0f, 0x0a, 0x0b, 0x5f, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x5f, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xdb, 0xa4, 0x06, 0x22, 0x24, 0x0a, 0x08, 0x4a,
	0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x61, 0x6d,
	0x6c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x65, 0x78, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x10,
	0x01, 0x22, 0x66, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x51, 0x75, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x66, 0x6c, 0x61, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0f,
	0x0a, 0x0b, 0x5f, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x5f, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xdc, 0xa4, 0x06, 0x22, 0xdc, 0x03, 0x0a, 0x14, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x3e, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2a, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x46, 0x4c, 0x41, 0x47, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44,
	0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x1a, 0x6a, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x22,
	0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x5f, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x5f, 0x5f, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xdd,
	0xa4, 0x06, 0x22, 0x64, 0x0a, 0x04, 0x46, 0x4c, 0x41, 0x47, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x4e, 0x6f, 0x64, 0x65, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x61, 0x78, 0x44, 0x69, 0x73,
	0x70, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6e, 0x74, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x46, 0x65, 0x65, 0x45, 0x72, 0x72, 0x10, 0x04, 0x22, 0x44, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x05,
	0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xde, 0xa4, 0x06, 0x22, 0x47,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x20, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0d,
	0x0a, 0x09, 0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x02, 0x49, 0x44, 0x10, 0xdf, 0xa4, 0x06, 0x22, 0x94, 0x01, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x34, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x64, 0x65,
	0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x20, 0x0a, 0x05,
	0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xe0, 0xa4, 0x06, 0x22, 0x47,
	0x0a, 0x11, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0d,
	0x0a, 0x09, 0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x02, 0x49, 0x44, 0x10, 0xe1, 0xa4, 0x06, 0x22, 0xd5, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x44,
	0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x1a, 0x57, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x33, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x20, 0x0a,
	0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x0d, 0x0a, 0x09, 0x5f, 0x5f, 0x69, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x02, 0x49, 0x44, 0x10, 0xe2, 0xa4, 0x06, 0x2a,
	0x70, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x10, 0x0a, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x10, 0x14, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x15, 0x12, 0x12, 0x0a,
	0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x10,
	0x1f, 0x2a, 0x59, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x10, 0x0a, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x49,
	0x6e, 0x47, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x10, 0x1f, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x10, 0x28, 0x42, 0x1b, 0x5a, 0x09,
	0x6d, 0x73, 0x67, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0xaa, 0x02, 0x0d, 0x73, 0x72, 0x63, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lobby_proto_rawDescOnce sync.Once
	file_lobby_proto_rawDescData = file_lobby_proto_rawDesc
)

func file_lobby_proto_rawDescGZIP() []byte {
	file_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_proto_rawDescData)
	})
	return file_lobby_proto_rawDescData
}

var file_lobby_proto_enumTypes = make([]protoimpl.EnumInfo, 15)
var file_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_lobby_proto_goTypes = []any{
	(PlayerStatus)(0),                        // 0: openproto.lobby.PlayerStatus
	(TableStatus)(0),                         // 1: openproto.lobby.TableStatus
	(ReqLoginLobby_MSGID)(0),                 // 2: openproto.lobby.ReqLoginLobby.MSGID
	(RespLoginLobby_MSGID)(0),                // 3: openproto.lobby.RespLoginLobby.MSGID
	(RespLoginLobby_FLAG)(0),                 // 4: openproto.lobby.RespLoginLobby.FLAG
	(ReqJoinQue_MSGID)(0),                    // 5: openproto.lobby.ReqJoinQue.MSGID
	(ReqJoinQue_JoinType)(0),                 // 6: openproto.lobby.ReqJoinQue.JoinType
	(RespJoinQue_MSGID)(0),                   // 7: openproto.lobby.RespJoinQue.MSGID
	(NotifyDispatchResult_MSGID)(0),          // 8: openproto.lobby.NotifyDispatchResult.MSGID
	(NotifyDispatchResult_FLAG)(0),           // 9: openproto.lobby.NotifyDispatchResult.FLAG
	(ReqLogoutLobby_MSGID)(0),                // 10: openproto.lobby.ReqLogoutLobby.MSGID
	(RespLogoutLobby_MSGID)(0),               // 11: openproto.lobby.RespLogoutLobby.MSGID
	(NotifyTableStatus_MSGID)(0),             // 12: openproto.lobby.NotifyTableStatus.MSGID
	(ReqUserDetailInfo_MSGID)(0),             // 13: openproto.lobby.ReqUserDetailInfo.MSGID
	(RespUserDetailInfo_MSGID)(0),            // 14: openproto.lobby.RespUserDetailInfo.MSGID
	(*UserBaseInfo)(nil),                     // 15: openproto.lobby.UserBaseInfo
	(*UserPropInfo)(nil),                     // 16: openproto.lobby.UserPropInfo
	(*UserGameBaseInfo)(nil),                 // 17: openproto.lobby.UserGameBaseInfo
	(*UserPlayingInfo)(nil),                  // 18: openproto.lobby.UserPlayingInfo
	(*UserMetaInfo)(nil),                     // 19: openproto.lobby.UserMetaInfo
	(*TableInfo)(nil),                        // 20: openproto.lobby.TableInfo
	(*ReqLoginLobby)(nil),                    // 21: openproto.lobby.ReqLoginLobby
	(*RespLoginLobby)(nil),                   // 22: openproto.lobby.RespLoginLobby
	(*ReqJoinQue)(nil),                       // 23: openproto.lobby.ReqJoinQue
	(*RespJoinQue)(nil),                      // 24: openproto.lobby.RespJoinQue
	(*NotifyDispatchResult)(nil),             // 25: openproto.lobby.NotifyDispatchResult
	(*ReqLogoutLobby)(nil),                   // 26: openproto.lobby.ReqLogoutLobby
	(*RespLogoutLobby)(nil),                  // 27: openproto.lobby.RespLogoutLobby
	(*NotifyTableStatus)(nil),                // 28: openproto.lobby.NotifyTableStatus
	(*ReqUserDetailInfo)(nil),                // 29: openproto.lobby.ReqUserDetailInfo
	(*RespUserDetailInfo)(nil),               // 30: openproto.lobby.RespUserDetailInfo
	nil,                                      // 31: openproto.lobby.UserPropInfo.PropsEntry
	nil,                                      // 32: openproto.lobby.UserMetaInfo.IntMetaEntry
	nil,                                      // 33: openproto.lobby.UserMetaInfo.StrMetaEntry
	(*NotifyDispatchResult_TablePlayer)(nil), // 34: openproto.lobby.NotifyDispatchResult.TablePlayer
	nil,                                      // 35: openproto.lobby.RespUserDetailInfo.UsersEntry
}
var file_lobby_proto_depIdxs = []int32{
	31, // 0: openproto.lobby.UserPropInfo.props:type_name -> openproto.lobby.UserPropInfo.PropsEntry
	0,  // 1: openproto.lobby.UserPlayingInfo.player_status:type_name -> openproto.lobby.PlayerStatus
	32, // 2: openproto.lobby.UserMetaInfo.int_meta:type_name -> openproto.lobby.UserMetaInfo.IntMetaEntry
	33, // 3: openproto.lobby.UserMetaInfo.str_meta:type_name -> openproto.lobby.UserMetaInfo.StrMetaEntry
	1,  // 4: openproto.lobby.TableInfo.table_status:type_name -> openproto.lobby.TableStatus
	4,  // 5: openproto.lobby.RespLoginLobby.flag:type_name -> openproto.lobby.RespLoginLobby.FLAG
	15, // 6: openproto.lobby.RespLoginLobby.base_info:type_name -> openproto.lobby.UserBaseInfo
	16, // 7: openproto.lobby.RespLoginLobby.props:type_name -> openproto.lobby.UserPropInfo
	19, // 8: openproto.lobby.RespLoginLobby.meta_info:type_name -> openproto.lobby.UserMetaInfo
	6,  // 9: openproto.lobby.ReqJoinQue.join_type:type_name -> openproto.lobby.ReqJoinQue.JoinType
	9,  // 10: openproto.lobby.NotifyDispatchResult.flag:type_name -> openproto.lobby.NotifyDispatchResult.FLAG
	34, // 11: openproto.lobby.NotifyDispatchResult.players:type_name -> openproto.lobby.NotifyDispatchResult.TablePlayer
	1,  // 12: openproto.lobby.NotifyTableStatus.status:type_name -> openproto.lobby.TableStatus
	35, // 13: openproto.lobby.RespUserDetailInfo.users:type_name -> openproto.lobby.RespUserDetailInfo.UsersEntry
	15, // 14: openproto.lobby.RespUserDetailInfo.UsersEntry.value:type_name -> openproto.lobby.UserBaseInfo
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_lobby_proto_init() }
func file_lobby_proto_init() {
	if File_lobby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lobby_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserPropInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UserGameBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UserPlayingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UserMetaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ReqLoginLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RespLoginLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ReqJoinQue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RespJoinQue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyDispatchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ReqLogoutLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RespLogoutLobby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyTableStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ReqUserDetailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RespUserDetailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*NotifyDispatchResult_TablePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_proto_rawDesc,
			NumEnums:      15,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_proto_depIdxs,
		EnumInfos:         file_lobby_proto_enumTypes,
		MessageInfos:      file_lobby_proto_msgTypes,
	}.Build()
	File_lobby_proto = out.File
	file_lobby_proto_rawDesc = nil
	file_lobby_proto_goTypes = nil
	file_lobby_proto_depIdxs = nil
}
